STORM-IRIT/Radium-Engine

Applications/MainApplication/Gui/MainWindow.cpp, Applications/MainApplication/Gui/MainWindow.hpp, Applications/MainApplication/Gui/ui/MainWindow.ui, Applications/MainApplication/MainApplication.hpp, src/Core/Math/LinearAlgebra.hpp, src/Core/Math/LinearAlgebra.inl, src/Core/Mesh/MeshPrimitives.cpp, src/Core/Utils/File/FileManager.hpp, src/Engine/Managers/SignalManager/SignalManager.cpp, src/Engine/Managers/SignalManager/SignalManager.hpp, src/Engine/Managers/SystemDisplay/SystemDisplay.hpp, src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.cpp, src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.hpp
* Mesh export button in UI 
* Capsule primitive in Debug Display
* getNormAndNormaiize functions in Core
* engine signals protected by mutexes.
=> Mesh export button + a few other features

CMakeLists.txt, CMakeModules/CompileFlags.cmake, src/Core/Image/stb_image.h
Fix the only warning in main code
Fixes #125
=> Add a warning as error option

src/Engine/Renderer/RenderTechnique/ShaderConfigFactory.cpp, src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp
Fix shader combobox display
Make ShaderConfigFactory register the ShaderConfig created on find miss in getShaderConfig() (only if non-empty name)
=> Fix shader combobox display

CMakeLists.txt, CMakeModules/CompileFlags.cmake, src/Core/Animation/Skinning/RotationCenterSkinning.cpp, src/Core/CoreMacros.hpp, src/Core/Log/Log.hpp, src/Core/Math/RayCast.inl, src/Core/Mesh/MeshUtils.cpp, src/Core/Mesh/Wrapper/Convert.cpp, src/Core/Tasks/TaskQueue.cpp, src/Engine/Entity/Entity.cpp, src/Engine/Entity/Entity.hpp, src/Engine/Managers/EntityManager/EntityManager.hpp, src/Engine/Renderer/Mesh/Mesh.cpp, src/GuiBase/Viewer/Viewer.cpp, src/Tests/CoreTests/Geometry/GeometryTests.hpp
This branch includes fixes to windows build and a rework of asserts to fix #137 and #167
=> Assert rework

Applications/MainApplication/MainApplication.cpp, Plugins/Skinning/src/SkinningComponent.cpp
=> replace on debug with on assert

Applications/MainApplication/Gui/MainWindow.cpp, Applications/MainApplication/Gui/ui/MainWindow.ui
=> change double spin box to label (nicer gui)

src/Core/Mesh/MeshPrimitives.inl
=> Fix torus mesh indices

Applications/MainApplication/Gui/MainWindow.cpp, Applications/MainApplication/MainApplication.cpp, src/Core/Math/LinearAlgebra.hpp, src/Core/Math/LinearAlgebra.inl, src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.cpp, src/GuiBase/Viewer/Gizmo/Gizmo.hpp, src/GuiBase/Viewer/Gizmo/GizmoManager.cpp, src/GuiBase/Viewer/Gizmo/GizmoManager.hpp, src/GuiBase/Viewer/Gizmo/RotateGizmo.cpp, src/GuiBase/Viewer/Gizmo/RotateGizmo.hpp, src/GuiBase/Viewer/Gizmo/TranslateGizmo.cpp, src/GuiBase/Viewer/Gizmo/TranslateGizmo.hpp
This PR contains two commits 
* one that uses eigen::ref for some functions in Algebra
* one that replaces the current behaviour of gizmos with a more sensible one.
=> Gizmos hide

Applications/MainApplication/Gui/MainWindow.cpp, Applications/MainApplication/Gui/MainWindow.hpp, Applications/MainApplication/Gui/ui/MainWindow.ui
Also change Renderer selection from QComboBox to Menu QActions ;
and some minor code cleanup ;
=> Change Plugin Widget container from QToolBox to QTabWidget ;

Plugins/Animation/src/AnimationComponent.cpp, Plugins/Animation/src/AnimationComponent.hpp, Plugins/Dummy/src/DummyTask.hpp, Plugins/FancyMesh/src/FancyMeshComponent.cpp, Plugins/FancyMesh/src/FancyMeshComponent.hpp, Plugins/Skinning/src/SkinningComponent.cpp, Plugins/Skinning/src/SkinningComponent.hpp, src/Engine/Managers/EntityManager/EntityManager.cpp, src/Engine/RadiumEngine.cpp, src/Engine/Renderer/Mesh/Mesh.cpp, src/Engine/Renderer/Mesh/Mesh.hpp, src/Engine/Renderer/RenderTechnique/ShaderProgramManager.cpp, src/Engine/Renderer/RenderTechnique/ShaderProgramManager.hpp, src/Engine/Renderer/Renderer.cpp, src/Engine/Renderer/Renderers/ForwardRenderer.hpp, src/GuiBase/Viewer/CameraInterface.hpp, src/GuiBase/Viewer/TrackballCamera.cpp, src/GuiBase/Viewer/TrackballCamera.hpp, src/GuiBase/Viewer/Viewer.cpp, src/GuiBase/Viewer/Viewer.hpp
Simplify new renderers creation
=> Accessor and ownrenderer

src/Core/Mesh/MeshPrimitives.cpp, src/Core/Mesh/MeshUtils.cpp
The end caps triangles were duplicated, with one having area ~0.
Fixes #116
=> Fix capsule primitive's degenerate triangles

.gitmodules
Update globject repos to master
=> Hotfix issue #251

Docs/Doxyfile.in, Docs/radium-as-submodule.md
for review to check everything is correct ;)
=> doc to use radium-as-submodule of your own project

src/Engine/Managers/EntityManager/EntityManager.hpp, src/Engine/Managers/SystemDisplay/SystemDisplay.cpp, src/GuiBase/BaseApplication.cpp
=> At least one thread for taskQueue, change assert in SystemDisplay.

Shaders/Picking.frag.glsl, src/Engine/Renderer/Renderer.cpp, src/GuiBase/Viewer/Viewer.cpp
Apparently, issue #295 is due to the "discard" command, at least on Windows.
=> Fix picking on Windows ;

.travis.yml
- [x ] Is the Pull-Request done against the right branch:
- [ x] The commit message follows our guidelines
Add token to get travis notifications in slack room
no
=> Add slack notifications in travis configuration

Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp, Plugins/MeshFeatureTracking/src/MeshFeatureTrackingPlugin.cpp
Minor code cleanup ;
When selecting features with the circle selection, the feature tracking sphere was displayed though it should not.
=> Fix MeshFeatureTrackingPlugin sphere ;

src/Engine/Managers/EntityManager/EntityManager.cpp
Fixes #307
Fixes entity management to deal with removal (see #308)
=> Fix entity manager

Applications/HelloRadium/CMakeLists.txt, Applications/MainApplication/CMakeLists.txt, Applications/SimpleSubdivideExample/CMakeLists.txt, Plugins/Animation/CMakeLists.txt, Plugins/Dummy/CMakeLists.txt, Plugins/FancyMesh/CMakeLists.txt, Plugins/MeshFeatureTracking/CMakeLists.txt, Plugins/MeshPaint/CMakeLists.txt, Plugins/Skinning/CMakeLists.txt, src/CMakeLists.txt
CMake: Finding Qt 5 the “Right Way”  
https://blog.kitware.com/cmake-finding-qt5-the-right-way/
=> CMake: Finding Qt 5 the “Right Way”

src/Engine/Renderer/Renderers/ForwardRenderer.hpp
Maybe it is not a good idea, but I have derived ForwardRenderer. So having it final is not fine for me.
(final was introduce in b885c5957)
=> Final is not the solution.

Applications/MainApplication/Gui/MainWindow.cpp
Remake of #303 .
The clear instruction on the `SelectionManager` was not the correct one.
=> Fix crash on clearScene ;

Docs/Doxyfile.in, Docs/develWithRadium.md, Docs/mesh.md, Plugins/Skinning/src/SkinningComponent.cpp, src/Core/Animation/Skinning/RotationCenterSkinning.cpp, src/Core/Mesh/DCEL/Face.hpp, src/Core/Mesh/DCEL/Face.inl, src/Core/Mesh/DCEL/FullEdge.hpp, src/Core/Mesh/DCEL/FullEdge.inl, src/Core/Mesh/DCEL/HalfEdge.hpp, src/Core/Mesh/DCEL/HalfEdge.inl, src/Core/Mesh/DCEL/Operations/EdgeSplit.cpp, src/Core/Mesh/DCEL/Vertex.hpp, src/Core/Mesh/DCEL/Vertex.inl, src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.cpp, src/Core/Mesh/TriangleMesh.hpp, src/Core/Mesh/TriangleMesh.inl, src/Core/Mesh/Wrapper/Convert.cpp, src/Core/Utils/Attribs.hpp, src/Engine/Renderer/Mesh/Mesh.cpp, src/Engine/Renderer/Mesh/Mesh.inl, src/Engine/Renderer/RenderObject/RenderObject.cpp, src/Engine/Renderer/Renderer.cpp, src/Tests/CoreTests/src/Mesh.hpp
In the assignment operators of TriangleMesh, add the missing return 
Fix wrong material binding when doing picking (segfault when doing picking in a complex scene with lot of different materials)
=> Fix pr#345

src/Engine/Renderer/Renderer.cpp
=> Keep background alpha when taking snapshots ;

src/Engine/Renderer/Renderer.cpp, src/Engine/Renderer/Renderer.hpp, src/GuiBase/BaseApplication.cpp, src/GuiBase/Viewer/Viewer.cpp
Nope, it's a small fix that do not change current behavior
Nope, it's a small fix that do not change current behavior
"bug" fix : use unique_ptr instead of raw ptr (that force the caller to delete allocated memory.
Also use human readable month integer ;)
new and free
month are between 0-11 in dir name
* **What is the new behavior (if this is a feature …
=> Grab frame unique ptr

cmake/CompileFlags.cmake
Improve the way cmake will configure the compiler for C++17 requierements
under gcc, cmake configure the CXX_FLAGS with-std=gnu++17
under gcc, cmake configure the CXX_FLAGS with-std=c++17
No
=> Fix C++17 requirements

Shaders/Materials/BlinnPhong/BlinnPhongMaterial.glsl
Fixes regression introduced by #389.
=> Hotfix #393

src/Core/Utils/Log.hpp, src/Engine/Renderer/OpenGL/OpenGL.hpp, src/GuiBase/TreeModel/TreeModel.cpp
=> FIX. Add namespace for LOG.

src/GuiBase/BaseApplication.cpp
Several files can now be loaded when using the main-app in command line:
`./main-app -f file1.ext -f file2.ext -f file3.ext`
We can only load one single file.
Several files can now be loaded.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application …
=> Load several files at startup

src/Core/Utils/Color.hpp
Compilation issues of expressions involving colors.
fix issue #435
=> fix issue #435 - Colors: compilation issues

Configs/alternative.xml, Configs/default.xml, scripts/pre-commit-clang-format.sh, src/GuiBase/Utils/KeyMappingManager.cpp, src/GuiBase/Utils/KeyMappingManager.hpp, src/GuiBase/Viewer/Gizmo/GizmoManager.cpp
Fix some KeyMappingManager issues.
Replace #445 for KeyMapping ... so we can discuss aabb only on #445, and fix here keyMappingIssues
=> Keymappingmanager fixes

src/GuiBase/Utils/KeyMappingManager.cpp, src/GuiBase/Viewer/TrackballCamera.hpp
=> More info in KeyMapping Manager message and remove not used action.

.github/stale.yml
Add configuration file for github probot/stale. 
Github issues and PR last open forever
Probot/stale mark as stale and then close PR and issues without activities.
=> Add configuration file for probot/stale

.gitignore, scripts/pre-commit-clang-format.sh
Change the pre commit script to non interactive. Interactive script have issue with git gui or other ide.
The script format and stage the modified section of the commit. If modifications are detected, it stops the commit operation so you can inspect before commit again.
I also cleanup gitignore file, since we are compiling out of source tree, and we want resources files to be available on git status (at least I do).
=> Cleanup conf

src/Core/Geometry/TopologicalMesh.cpp, src/Core/Utils/Attribs.cpp, src/Core/Utils/Attribs.hpp
Bug fix
memory leak
use unique_ptr to have auto delete
Supersede #471, resolve #470 
To be tested
=> Use unique_ptr in AttribManager.

.travis.yml
Commit to be fixed later: the `before_deploy` command has been moved to `install` for testing
=> Test: fixing .travis

.travis.yml
=> Update doc deployment

appveyor.yml
=> tentative fix for appveyor: going to ninja

doc/basics/compilation.md
Just one line of doc after user feedback.
=> doc add make install

doc/developer/buildchain.md
closes #491
Simple doc update.
=> Update doc to current behavior.

src/Core/Geometry/TopologicalMesh.cpp, src/Core/Geometry/TriangleMesh.hpp, src/Core/Geometry/TriangleMesh.inl
=> Remove useless friendship between AttribArrayGeometry and TopologicalMesh

CMakeLists.txt, cmake/Config.cmake.in, doc/CMakeLists.txt, doc/basics/compilation.md, src/GuiBase/Viewer/Viewer.cpp, src/GuiBase/Viewer/Viewer.hpp, src/IO/CMakeLists.txt
Small Fix PR.
cmake feature, one rename
There is two bundle dir
Bundle-*
and 
Bundle-*-Debug
Bundle dir is extracted from cmake_build_type
Bundle-*-CMAKE_BUILD_TYPE
if no CMAKE_BUILD_TYPE is provided use Release.
Also use release for assimp if CMAKE_BUILD_TYPE is RelWithDebInfo or MinSizeRel (this one as not been checked ...)
Correct a typo in Viewer.
=> Cmakestuff

src/Core/Asset/GeometryData.inl, src/Core/Resources/Resources.cpp, src/GuiBase/Utils/Keyboard.hpp
=> fix resource path for windows ;

doc/basics/compilation.md, src/Core/CMakeLists.txt, src/Core/Utils/Log.hpp
Adds an option to disable Radium Log messages.
When the option is set to `ON` / `TRUE`, Radium log messages coming from 
```[c++]
LOG( log* ) << ... ;
```
are disabled.
=> Add option to disable log messages ;

src/Engine/Component/GeometryComponent.cpp, src/Engine/Component/GeometryComponent.hpp
=> Fix issue 510;

Shaders/Materials/Lambertian/Lambertian.glsl, Shaders/Materials/Plain/Plain.frag.glsl, Shaders/Materials/Plain/Plain.glsl, Shaders/Materials/VertexAttribInterface.frag.glsl, src/Engine/Component/GeometryComponent.cpp, src/Engine/Component/GeometryComponent.hpp, src/Engine/Renderer/RenderObject/RenderObject.cpp, src/Engine/Renderer/RenderTechnique/RenderParameters.hpp, src/Engine/Renderer/RenderTechnique/RenderParameters.inl, src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp, src/Engine/Renderer/RenderTechnique/ShaderProgram.hpp, src/GuiBase/Viewer/Gizmo/Gizmo.cpp, src/GuiBase/Viewer/Gizmo/Gizmo.hpp, src/GuiBase/Viewer/Gizmo/RotateGizmo.cpp, src/GuiBase/Viewer/Gizmo/ScaleGizmo.cpp, src/GuiBase/Viewer/Gizmo/TranslateGizmo.cpp
There is a PR on Radium Apps that follow this one.
Code refactoring to have a better usage of the Material interface for gizmos rendering.
Fix link problem on shaders for undefined fragment input
=> This PR solve the issue #505 and #512

doc/developer/conventions.md, src/Core/Utils/Index.inl, src/Engine/Component/GeometryComponent.cpp, src/Engine/Component/GeometryComponent.hpp, src/Engine/Renderer/Camera/Camera.cpp, src/Engine/Renderer/Material/VolumetricMaterial.hpp, src/Engine/Renderer/RenderObject/RenderObject.hpp, src/Engine/Renderer/RenderTechnique/RenderTechnique.cpp, src/Engine/Renderer/RenderTechnique/RenderTechnique.hpp, src/Engine/Renderer/Renderers/DebugRender.hpp, src/Engine/Renderer/Texture/Texture.cpp
Fixes some of the forgotten review of #476
=> Todos doc and comment.

src/Engine/Renderer/Material/Material.hpp, src/Engine/Renderer/Material/Material.inl
...  from any software part.
This will allow to fix issue https://github.com/STORM-IRIT/Radium-Apps/issues/12
This PR allow applications or components to ask for OpenGL state update on Materials.
=> Material openGL state could be forced to be updated

doc/Doxyfile.in, doc/developer/buildchain.md, doc/developer/develWithRadium.md
Updated small typos into documentation
=> Documentation small update

cmake/filelistEngine.cmake, src/Engine/Renderer/RenderTechnique/RenderParameters.hpp, src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp, src/Engine/Renderer/RenderTechnique/ShaderProgram.hpp, src/Engine/Renderer/RenderTechnique/ShaderProgram.inl
refactor
overloaded function with exact same body
use template
nope
=> [engine] Shader program refactor: use templated setUniform.

cmake/radium_setup_functions.cmake, doc/developer/keymapping.md, src/Engine/Managers/ComponentMessenger/ComponentMessenger.inl, src/Engine/RaEngine.hpp, src/Engine/RadiumEngine.cpp, src/Engine/RadiumEngine.hpp, src/Engine/Renderer/Displayable/VolumeObject.cpp, src/Engine/Renderer/Mesh/Mesh.hpp, src/Engine/Renderer/OpenGL/OpenGL.hpp, src/Engine/Renderer/RenderTechnique/ShaderConfigFactory.cpp, src/Engine/Renderer/RenderTechnique/ShaderConfiguration.hpp, src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp, src/Engine/Renderer/RenderTechnique/ShaderProgramManager.cpp, src/Engine/Renderer/Renderer.cpp, src/Engine/Renderer/Texture/Texture.cpp, src/Engine/Renderer/Texture/Texture.hpp, src/Engine/Renderer/Texture/TextureManager.cpp, src/Engine/Renderer/Texture/TextureManager.hpp, src/GuiBase/RaGuiBase.hpp, src/GuiBase/Utils/KeyMappingManager.cpp, src/GuiBase/Viewer/Viewer.cpp, src/GuiBase/Viewer/Viewer.hpp, tests/ExampleApps/DrawPrimitivesApp/main.cpp, tests/ExampleApps/HelloRadium/main.cpp, tests/ExampleApps/SimpleAnimationApp/main.cpp
Bug fix, small feature update. 
Also this PR allows to override viewer keymapping in derived class.
Refactor Viewer to have coherent ordering.
Move getBackground out of slot.
I have a working example on my side, but if not appropriate, this PR can be splitted in two.
settings file is not loaded by default
shader version is lost on reload
now it seems to work ;)
Todo :
=> Several fix and refactors (keymapping conf, shader reload, viewer)

src/Engine/Renderer/Mesh/Mesh.hpp, src/Engine/Renderer/Mesh/Mesh.inl, src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.cpp, src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.hpp, tests/ExampleApps/DrawPrimitivesApp/minimalradium.cpp
Change Primitive parameter to correspond to debug macro.
Continue the transformation of DrawPrimitiives functions to use new core mesh/engine mesh interaction.
partially closes  #74
=> Engine mesh

tests/ExampleApps/SimpleAnimationApp/minimalapp.cpp, tests/ExampleApps/SimpleAnimationApp/minimalradium.cpp
Configure the RadiumEngine so that it is the one managing time
=> fix SimpleAnim w.r.t. time management in RadiumEngine

.github/workflows/pull-request.yml
Small typo in echo, make sh trying to evaluate instead of print.
=> [git] Typo in workflow echo, update name.

cmake/radium_setup_functions.cmake, doc/basics/compilation.md, src/Engine/Renderer/Mesh/Mesh.hpp
Doc update
Current build instruction described in documentation for MSVC+ninja do not work on VS 2019.
Update doc
no
=> Update compilation documentation + Fix debugging for Microsoft OS

cmake/Windeployqt.cmake, cmake/radium_setup_functions.cmake
Update cmake scripts to deploy qt-based application on windows
Use cmake `fixup_bundle` for deployment: misses several system libraries
*Add* call to windeployqt to complete the process operated by `fixup_bundle`.
No
=> Add windeployqt

src/GuiBase/Timeline/Timeline.ui
=> Fixes issue #596 (Timeline UI)

cmake/radium_setup_functions.cmake
Was breaking cmake package.
* **What is the current …
=> Add missing path when including Windeployqt

cmake/radium_setup_functions.cmake, doc/developer.md, doc/developer/cmakeutilities.md, doc/developer/develWithRadium.md, src/CMakeLists.txt, src/Core/CMakeLists.txt, src/Engine/CMakeLists.txt, src/GuiBase/CMakeLists.txt, src/IO/CMakeLists.txt, src/PluginBase/CMakeLists.txt, tests/ExamplePluginWithLib/Upstream/Library/CMakeLists.txt, tests/ExamplePluginWithLib/Upstream/Library/ExampleLibrary.cpp, tests/ExamplePluginWithLib/Upstream/Library/ExampleLibraryUpstream-Config.cmake.in, tests/ExamplePluginWithLib/Upstream/Library/LibraryResources/welcome.txt
Closes #590
Ready to review (seems that there is a lot of typos ;) )
Status of the documentation:
While writing the documentation, I found the following problems that I fixed (some remains but are out of topic of this PR) in the cmake scripts
Windows scripts will be verified after PR #594 is merged
* …
=> cmake functions documentation 

.github/workflows/pull-request.yml
Fix git hub action (forget one script to update to new external directory structure).
=> [github] update action again, forget one file

doc/basics/compilation.md
=> Msvc2017 cmake compilation

.github/workflows/pull-request-ci.yml, src/Core/Asset/FileData.hpp, src/Core/Asset/LightData.hpp, src/Core/Geometry/Volume.hpp, src/Core/Utils/StackTrace.cpp, src/Engine/Component/GeometryComponent.hpp, src/Engine/Managers/ComponentMessenger/ComponentMessenger.inl, src/Engine/Renderer/RenderTechnique/RenderTechnique.cpp, src/Engine/Renderer/Renderer.hpp, src/Engine/Renderer/Renderers/DebugRender.cpp, src/Engine/Renderer/Renderers/DebugRender.hpp, src/GuiBase/Timeline/TimelineScrollArea.cpp, src/GuiBase/Timeline/TimelineTimeScale.cpp, src/GuiBase/TreeModel/TreeModel.cpp, src/GuiBase/Viewer/FlightCameraManipulator.hpp, src/GuiBase/Viewer/Gizmo/Gizmo.hpp, tests/unittest/Core/observer.cpp
=> fix issue #628

src/Engine/Renderer/Mesh/Mesh.hpp, src/Engine/Renderer/Mesh/Mesh.inl, src/Engine/Renderer/RenderTechnique/ShaderConfiguration.cpp, src/Engine/Renderer/RenderTechnique/ShaderConfiguration.hpp, src/Engine/Renderer/Renderers/ForwardRenderer.cpp
Bug Fix
PolyMesh return 0 faces, which makes them treated as a point cloud, with geometry shader
return the number of faces from core geometry
Hot fix
need further re factoring to clean
=> Fix polymesh

cmake/Windeployqt.cmake
=> Attempt to make winqtdeploy more robust

src/Engine/Managers/ComponentMessenger/ComponentMessenger.inl
PR #629 breaks debug build due to parameter anonymized.
This PR anonymize it only for Release build.
=> Allow to build Radium in Debug mode

.github/workflows/pull-request-ci.yml, .github/workflows/pull-request.yml, README.md, cmake/Windeployqt.cmake, doc/main.md
This pull request add new badges according to the new CI with github actions.
Before merge, we need to remove pull_request selection in push_master.yml workflow.
The resulting badges are shown gere https://github.com/STORM-IRIT/Radium-Engine/tree/workflow-badges
=> Workflow badges

src/Core/Asset/HandleToSkeleton.cpp, src/Core/Containers/Grid.hpp, src/Core/Math/DualQuaternion.hpp, src/Core/Tasks/TaskQueue.cpp, src/Core/Tasks/TaskQueue.hpp, src/Core/Utils/Color.hpp, src/GuiBase/SelectionManager/SelectionManager.hpp, src/GuiBase/TreeModel/EntityTreeModel.hpp, src/GuiBase/TreeModel/TreeModel.hpp
small style and fix suggested by codacy.
Only the first commit is "important" as it may deref an invalid ptr.
No breaking changes.
=> Fix from codacy

src/Engine/RadiumEngine.cpp, src/Engine/RadiumEngine.hpp
Fix time management issue in forward-backward mode.
* **What …
=> Fix time management for the forward-backward mode ;

doc/basics/compilation.md
Update the documentation about:
- the minimum version of …
=> update doc w.r.t. tools version and CMAKE_BUILD_PARALLEL_LEVEL

.github/workflows/deploy-doc.yml
=> [github] hot fix.

src/IO/TinyPlyLoader/TinyPlyFileLoader.cpp
Cppcheck reports a possible dereference of nullptr, which is right.
After trying to understand the code flow attended, I change the tests so that It works as I think it should.
Also this PR introduce code refactor to have less redundancy, and should be more efficient, but firsts tests do not show loading time diminution.
At least one real test before accepting the PR.
-> done
=> [io] TinyPlyLoader refactor and cppcheck fix.

README.md
Current link to release is wrong.
* **What is the current …
=> Emphasis link with Radium-Release in readme

.github/workflows/deploy-doc.yml, doc/CMakeLists.txt
Simple sed base fix for documentation.
codecov svg image is wrongly inserted as an object instead of img.
patch index file so that it's img instead of object
nope
=> [github] Ugly fix for badge. Fix #652

CMakeLists.txt, cmake/coverageFunc.cmake, doc/developer/mesh.md, tests/unittest/Core/mesh.cpp
Mostly unit tests and also a bit of cmake fix
=> Unittest attrib

.github/workflows/pull-request-ci.yml, doc/basics/compilation.md, src/IO/CMakeLists.txt
=> Enable assimp by default.

src/Core/Utils/Attribs.cpp, src/GuiBase/BaseApplication.cpp, tests/unittest/Core/mesh.cpp
refactor
and also one test use 5 value instead of 3 (even if it do not trigger errors, it's not needed).
=> [tests] refactor mesh test

src/Core/Geometry/TopologicalMesh.cpp, src/Core/Geometry/TopologicalMesh.hpp, src/Core/Geometry/TopologicalMesh.inl, tests/unittest/Core/topomesh.cpp
Feature
* **What is the current behavior?** (You can also …
=> First attempt to expose a functor to handle non-manifold elements

.github/workflows/create-tag-from-dispatch.yml, .github/workflows/notify-radium-releases.yml
see https://github.com/STORM-IRIT/Radium-Releases/pull/10
=> Tag head commit when receiving dispatch event

external/CMakeLists.txt, external/Core/CMakeLists.txt, external/Engine/CMakeLists.txt, external/IO/CMakeLists.txt
=> Add dependencies between external targets

src/Core/Geometry/TopologicalMesh.cpp, src/Core/Geometry/TopologicalMesh.hpp, src/Core/Geometry/TopologicalMesh.inl, tests/unittest/Core/topomesh.cpp
Bugfix
See #688 
Check if the mesh has normal attributes before copying them
--
=> Check if normals exists before accessing them (fix #688)

.github/workflows/pull-request-ci.yml, cmake/filelistCore.cmake, src/Core/Resources/Resources.cpp, src/Core/Utils/StdFilesystem.hpp, src/Gui/Utils/KeyMappingManager.cpp, src/Gui/Utils/KeyMappingManager.hpp, tests/integration/CMakeLists.txt, tests/integration/KeyMappingManager/main.cpp, tests/integration/data/inputs/keymapping-valid.xml, tests/integration/data/references/keymapping-valid.xml, tests/unittest/CMakeLists.txt, tests/unittest/Gui/keymapping.cpp, tests/unittest/data/dummy1.xml, tests/unittest/data/dummy2.xml, tests/unittest/data/keymapping-bad-main.xml, tests/unittest/data/keymapping-bad-tag.xml, tests/unittest/data/keymapping-double-actions.xml, tests/unittest/data/keymapping-invalid.xml, tests/unittest/data/keymapping-valid.xml
unit tests
keymapping manager is not tested at all
basic loading is tested
nope.
todo (now of for the futur depending on time)
=> Keymapping unit tests

doc/developer/mesh.md, doc/images/wedge-degen.svg, src/Core/Geometry/TopologicalMesh.inl, tests/unittest/Core/topomesh.cpp
Bug fix
When converting to Topological Meshes, some non manifold faces are detected, some raise an assert (on purpose according to openmesh doc, see commit messages).
We pre process the index list to skip badly formed faces.
For the current version, it removes the faces (since inputs are only triangles, bad formed faces drops down to lines which are not handled)
When #589 will be merged, it can add faces that "loose" some vertices, but are still relevant.
* **Does this PR introduce a breaking change?** (What …
=> Fix topo complex

doc/CMakeLists.txt, src/Core/Geometry/Volume.hpp, src/Core/Utils/Attribs.hpp
Feature
There is no command to describe the complexity of a function
Add new command `\complexity` for doxygen.
- 
=> [doc] Add complexity command

src/Core/Geometry/MeshPrimitives.cpp, src/Core/Geometry/TriangleMesh.hpp, src/Core/Utils/Attribs.hpp, src/Engine/Data/Mesh.inl, src/Engine/Rendering/ForwardRenderer.cpp, src/Gui/BaseApplication.cpp, src/IO/TinyPlyLoader/TinyPlyFileLoader.cpp, tests/unittest/Core/topomesh.cpp
Clean API (remove unused friend link), 
Remove warning when compiling in debug mode
Improve API: store indices as VectorArray to add `getMap()`
no
=> Minor fixes

src/Engine/Data/Mesh.hpp, src/Engine/Scene/GeometryComponent.hpp, src/Engine/Scene/GeometryComponent.inl, src/Gui/RadiumWindow/SimpleWindow.cpp, tests/ExampleApps/CMakeLists.txt, tests/ExampleApps/DrawPrimitivesApp/minimalradium.cpp
Improve DrawPrimitiveApp with new elements, and config variables
Also hot fix of uninit boolean in ForwardRenderer...
Everything is drawn.
Add radium logo, plus a set of boolean to select what is drawn.
nope
Also add a meshFactory function to generate a mesh from AssetData (without a component).
If ok we can use this function in Component to avoid code …
=> Draw primitives app

.github/workflows/pull-request-ci.yml, doc/basics/compilation.md
CI hot fix.
Another solution is to stick to 18.04
=> [github] update gcc according to last ubuntu image

src/IO/TinyPlyLoader/TinyPlyFileLoader.cpp
PR #721 has some dead code, remove !?
=> [io] remove unneeded template

src/Engine/Rendering/ForwardRenderer.cpp
=> removed a warning due to processLineMesh lambda

src/Core/Containers/BVH.hpp, src/Core/Geometry/Curve2D.inl, src/Core/Geometry/RayCast.cpp, src/Core/Geometry/TopologicalMesh.hpp, src/Core/Geometry/deprecated/TopologicalMesh.cpp, src/Engine/Scene/CouplingSystem.hpp, tests/integration/CMakeLists.txt, tests/integration/includes.cpp.in, tests/unittest/Core/topomesh.cpp
Add an integration test to check all includes are include-able, retrieve the include list from each lib lifelist.
Also small fixed driven by codacy.
Nothing ground breaking.
=> Test and small fixes

src/Core/Asset/HandleData.inl, src/IO/AssimpLoader/AssimpHandleDataLoader.cpp
Do not load empty skeleton in assimp loader.
=> [IO] Fix assimp loading : do not load empty skeleton

CMakeLists.txt, cmake/filelistEngine.cmake, src/Engine/Rendering/Renderer.cpp, src/Engine/Rendering/Renderer.hpp, src/Engine/Rendering/Renderer.inl, src/Gui/Utils/PickingManager.cpp, src/Gui/Viewer/Viewer.cpp, tests/ExampleApps/CMakeLists.txt, tests/ExampleApps/PickingDemoApp/CMakeLists.txt, tests/ExampleApps/PickingDemoApp/main.cpp
API improvements + doc
PickingResult store separately the indices of picked faces, vertices and edges.
Group face, vertex and edge id in a tuple to ease processing + add duplicate removal tools.
Change of API.
=> Improve picking usage

src/Core/Utils/Observable.hpp, tests/unittest/Core/observer.cpp
bug fix/feature
observable.attachMember work only for one arg method  (e.g. class::func(arg)) due to the usage of std::bind
variadic args are hard to forward.
Now it works, using a templated lamdba instanciation
=> Observable tests

src/Engine/Scene/CameraManager.cpp, src/Engine/Scene/CameraManager.hpp, src/Engine/Scene/CameraStorage.hpp, src/Gui/SelectionManager/SelectionManager.hpp
Potential bug fix.
Some forward declaration remains from old Engine structure, which may badly create ambiguous reference to classes.
Cleaned at least for two files ... but it may remains some other.
=> Fix forward declaration of Entity, Component, and Camera.

.github/workflows/guideline-checks.yml
comment was referring master instead of release-candidate.
Fixed.
=> Fix comment ci

src/Gui/Viewer/Viewer.cpp
=> [gui] Mark event VIEWER_TOGGLE_WIREFRAME caught to generate redraw event

src/Gui/BaseApplication.cpp, src/Gui/MainWindowInterface.hpp, src/Gui/Utils/KeyMappingManager.cpp, src/Gui/Utils/KeyMappingManager.hpp, src/Gui/Viewer/CameraManipulator.cpp, src/Gui/Viewer/CameraManipulator.hpp, src/Gui/Viewer/FlightCameraManipulator.cpp, src/Gui/Viewer/FlightCameraManipulator.hpp, src/Gui/Viewer/TrackballCameraManipulator.cpp, src/Gui/Viewer/TrackballCameraManipulator.hpp, src/Gui/Viewer/Viewer.cpp, src/Gui/Viewer/Viewer.hpp, tests/ExampleApps/CMakeLists.txt, tests/ExampleApps/KeyEventDemoApp/CMakeLists.txt, tests/ExampleApps/KeyEventDemoApp/main.cpp, tests/unittest/Gui/keymapping.cpp
All is in the title. Use `<F1>`  or `<F2>` keys to toggle colors.
=> [test] Add Custom KeyEvent demo

README.md
This PR add radium doi and bibtex to main readme.
=> [github] add doi to readme.

src/Core/Containers/AlignedAllocator.hpp, src/Core/CoreMacros.hpp
Fix compilation for Apple M1 and Nvidia Jetson.
Compilation fail due to improper macros and non portable code
Compilation pass on these platforms
No change for regular users.
=> Fix compilation for ARM platforms (Apple M1 and Nvidia Jetson Xavier)

src/Core/Containers/AlignedAllocator.hpp
Fix regression introduced in 54379586f9a4a54c4bc8e127e5af940f99da4213
Compilation warning due to unexpected token when evaluating preprocessor directives.
No more warning
The platform detection was still working, so no change on the client side.
=> [core] Fix preprocessor warning on windows

src/IO/AssimpLoader/AssimpFileLoader.cpp
Closes #807
Bug fix
See issue #807 
* **What is the current …
=> Remove FixInfacingNormals assimp process

cmake/Config.cmake.in
fix filename in Config.cmake.in
=> [cmake] fix install filename

.github/workflows/deploy-doc.yml, .gitmodules, doc/CMakeLists.txt, doc/basics/compilation.md
This PR adds doxygen-awsome-css as a submodule for doc, and use note instead of buggy bold to emphasis compilation instruction.
=> Doxygen awesome css

tests/external/CMakeLists.txt
Update Catch2 test suit, fixes #843
=> [cmake] update catch2

src/IO/VolumesLoader/VolumeLoader.cpp
Bug fix
Compilation of `VolumeLoader` fails on some platforms due to missing cast for Eigen Scalar type.
https://github.com/STORM-IRIT/Radium-Engine/runs/4844992814?check_suite_focus=true#step:15:3986
Cast has been added
No
=> Fix numeric cast in VolumeLoader

cmake/filelistCore.cmake, cmake/filelistIO.cmake, src/Core/Utils/ContainerIntrospectionInterface.hpp
Hot fix, missing new file in source lists.
Reviewers : Please check if new file in IO are meant to be added.
=> Add missing file in source list.

README.md, doc/main.md
Fix codacy badge link in readme and doc.
=> [doc] update codacy badge link

.github/workflows/push-master-ci.yml
=> [github] use token

.github/workflows/push-master-ci.yml
=> tmp rc-test

.github/workflows/push-master-ci.yml
=> fix skip ci

.github/workflows/build-matrix.yml, .github/workflows/coverage.yml, .github/workflows/deploy-doc.yml, .github/workflows/increase-version.yml, .github/workflows/notify-radium-releases.yml, .github/workflows/pull-request-ci.yml, .github/workflows/push-ci.yml, .github/workflows/push-rc-ci.yml, cmake/RadiumSetupFunctions.cmake
Try to make ci cleaner, and work with version bump before any other ci jobs on master and release candidate pushes.
=> Update CI, clean workflow regarding version bump.

doc/basics/dependencies.md, external/Core/CMakeLists.txt, external/Engine/CMakeLists.txt, external/IO/CMakeLists.txt
Doc update and minor fixes
First compilation might be tedious for some users
Improve doc and add minor fixes to make user life easier
No
=> Improve instruction first build

src/Core/Utils/ObjectWithSemantic.hpp
explicit is missing for  ObjectWithSemantic( const SemanticNameCollection& otherNames )
this PR adds the explicit keyword.
=> Fix implicit ctor

.github/workflows/build-matrix.yml, .github/workflows/coverage.yml, .github/workflows/pull-request-ci.yml
Skip python installation when installing qt
=> Attempt to fix broken Qt installation in CI

src/Core/Geometry/MeshPrimitives.cpp, src/Core/Geometry/MeshPrimitives.hpp, src/Core/Geometry/MeshPrimitives.inl
=> Quad tex coord

src/Engine/Data/RenderParameters.cpp, src/Engine/Data/RenderParameters.hpp, tests/unittest/CMakeLists.txt, tests/unittest/Engine/renderparameters.cpp
Bug fix and feature
render parameter concat do not replace values and misses some concatenation
all paramters are concatenated, and a new "copy" feature is added which replaces existing parameters values.
=> Render parameters

tests/ExampleApps/HeadlessDemo/CMakeLists.txt
=> [tests] fix #927

src/Engine/Data/RenderParameters.cpp, src/Engine/Data/RenderParameters.hpp, src/Engine/Data/ShaderProgram.cpp, src/Engine/Data/ShaderProgram.hpp, src/Engine/Data/ShaderProgram.inl
Kind of quick fix, improvement needed to do only necessary conversion, using template programming, is_same and enable_if, but I hade trouble making it right.
Bug fix
see #930 
=> [engine] fix #930, taking care if Scalar is double

src/Headless/OpenGLContext/OpenGLContext.cpp, src/Headless/OpenGLContext/OpenGLContext.hpp
This PR add a mouse move event listener for the optional glfw window of Headless::OpenGLContext
There is no way to catch mouse move event
Mouse move event can be catched by a user define callback, the same way other events.
No
=> Extend cli viewer (bis) : mouse move event listener

src/Headless/CMakeLists.txt, src/Headless/Config.cmake.in, src/Headless/OpenGLContext/OpenGLContext.hpp
This PR fix the version of the glfw dependency required by headless component.
Version searched is 3.2 but version used is 3.3
search for version 3.3
No
=> Fix glfw version required 

cmake/RadiumSetupFunctions.cmake
closes #946 
Allows to manage several resources directories per Radium artifact (library, plugin, application)
When a library with several resources directories declared (using the radium-cmake function install_target_resources), only the last declared is installed if this library is used as an helper-lib for a plugin or a dependency for other installable artifact.
A target store a list of associated resource …
=> fix multiple resources directories issue (#946)

.github/workflows/build-matrix.yml, .pre-commit-config.yaml, cmake/RadiumSetupFunctions.cmake, doc/CMakeLists.txt, doc/basics/compilation.md, doc/basics/dependencies.md, doc/developer/mesh.md, src/Core/Animation/LinearBlendSkinning.hpp, src/Core/Geometry/RayCast.cpp, src/Core/Geometry/RayCast.hpp, src/Core/Geometry/TopologicalMesh.hpp, src/Core/Geometry/deprecated/TopologicalMesh.hpp, src/Engine/Data/ShaderProgram.cpp, src/Engine/Data/ShaderProgram.inl, src/Engine/OpenGL.hpp, src/Gui/Utils/Keyboard.cpp, src/Gui/Utils/Keyboard.hpp, src/Gui/Viewer/Gizmo/Gizmo.hpp, src/Gui/Viewer/Viewer.cpp, src/Gui/Viewer/Viewer.hpp, src/IO/VolumesLoader/VolumeLoader.cpp, src/IO/VolumesLoader/pvmutils.cpp, tests/ExamplePluginWithLib/Upstream/Library/CMakeLists.txt, tests/unittest/Engine/renderparameters.cpp
small bug/feature fix
- configure radium lib includes current source dir, which makes includes not consistent accross different files, and are prone to name clash.
- one badly pre declared class
- some pass by const values instead of ref
fix theses
yes for the includes, may break client …
=> Small fixes

doc/basics/compilation.md
Add doc on how to configure visual studio to execute in the buildtree
=> documentation on how to execute in the build tree under windows/VisualStudio

README.md, src/Core/Geometry/MeshPrimitives.inl, src/Core/Math/LinearAlgebra.hpp, src/Core/Resources/Resources.cpp, src/Core/Types.hpp, src/Core/Utils/Attribs.hpp, src/Core/Utils/StdMapIterators.hpp, src/Engine/Data/BlinnPhongMaterial.inl, src/Engine/Data/Mesh.cpp, src/Engine/Data/Mesh.hpp, src/Engine/OpenGL.hpp, src/Engine/Scene/Component.cpp, src/Engine/Scene/ComponentMessenger.cpp, src/Engine/Scene/ComponentMessenger.hpp, src/Engine/Scene/LightStorage.hpp, src/Gui/AboutDialog/AboutDialog.ui, src/Gui/BaseApplication.cpp, src/Gui/BaseApplication.hpp, src/Gui/Timeline/TimelineScrollArea.cpp, src/Gui/Viewer/RotateAroundCameraManipulator.hpp, tests/ExampleApps/HelloRadium/main.cpp
Mostly fixes + precompiled headers
If needed I can split this PR in small parts (e.g. if some point need discussion, I'll split the ok part to a first PR, and we can discuss the rest).
* **Behavior changes**
Add getter for AttribArrayDisplayable's vao and vbo OpenGL's handle (e.g. for cudo interoperability).
Clean lambda capture (remove warning, also present in #950 ...) 
4b1de5209a [engine] fix forward decl RenderParameters
One miss forward declared class
8434cd6528 [engine] unregister component messaging on delete.
When removing a component, also unregister corresponding registered calls 
3d74db8a2b [engine] Add gl namespace to GL_ macros. …
=> Various small fixes

src/Engine/Scene/GeometryComponent.hpp, src/Engine/Scene/GeometryComponent.inl
Add LineMeshComponent, to allow the creation of Component based on LineMesh.
=> [engine] Add LineMeshComponent def.

external/Core/CMakeLists.txt
=> Fix nlohmann_json deleted branch issue

CMakeLists.txt
Remove example apps from coverage report so that source code of examples is not reported as not covered by tests
=> removes examples apps from coverage report

doc/CMakeLists.txt, doc/custom.css, doc/header.html
Update awesome-doxygen-css and configure nice features (day/night mode, copy code, anchors ...).
splitted from #1000
=> [doc] Update and tweak doxygen-awesome-css.

.github/workflows/deploy-doc.yml
Please check if the PR fulfills these requirements
Online documentation is ill-formed In release candidate due to wrong Doxygen version
Now use doxygen 1.9.3 which support the new functionalities introduced by #1001 
No, only GitHub actions.
=> Fix doxygen deploy

.github/workflows/deploy-doc.yml, .github/workflows/pull-request-ci.yml
Hot fix for doc. Hope it'll work.
=> [github] Use doxygen 1.9.1 (1.9.3 is buggy for pages), and fix badges.

examples/CMakeLists.txt, examples/TexturedQuadDynamic/CMakeLists.txt, examples/TexturedQuadDynamic/main.cpp, src/Core/Tasks/TaskQueue.cpp, src/Core/Tasks/TaskQueue.hpp, src/Engine/Data/Texture.cpp, src/Engine/Data/Texture.hpp, src/Engine/RadiumEngine.cpp, src/Engine/RadiumEngine.hpp, src/Engine/Rendering/Renderer.cpp, src/Gui/BaseApplication.cpp, tests/unittest/CMakeLists.txt, tests/unittest/Core/singleton.cpp, tests/unittest/Core/taskqueue.cpp
replace #982 with cleaner history.
=> Update texture data

doc/basics.md, doc/basics/compilation.md, doc/basics/dependencies.md
Update and detail a bit more windows command line instructions.
=> [doc] better command line instructions.

examples/CMakeLists.txt, examples/SimpleSkinning/CMakeLists.txt, examples/SimpleSkinning/main.cpp, src/Core/Geometry/MeshPrimitives.cpp, src/Core/Geometry/MeshPrimitives.hpp, src/Core/Math/LinearAlgebra.hpp, src/Core/Math/LinearAlgebra.inl, src/Core/Math/Math.hpp, src/Engine/Scene/SkeletonComponent.cpp, src/Engine/Scene/SkeletonComponent.hpp, src/Engine/Scene/SkinningComponent.hpp, tests/unittest/Core/algebra.cpp
It's hard to use skinning without loaded scene
Add new setters so that one can define all skinning data progamatically, with a simple example.
Fix checkInvalidNumbers (as far as I understand), add smoothstep
=> Simple skinning

doc/developer/timeline.md, examples/EntityAnimation/main.cpp, examples/SimpleAnimation/main.cpp, examples/SimpleSimulation/main.cpp, examples/SimpleSkinning/main.cpp, src/Core/Tasks/TaskQueue.cpp, src/Core/Tasks/TaskQueue.hpp, src/Engine/Data/Texture.cpp, src/Engine/RadiumEngine.cpp, src/Engine/RadiumEngine.hpp, src/Engine/Scene/CameraManager.cpp, src/Engine/Scene/SkeletonBasedAnimationSystem.cpp, tests/unittest/Core/taskqueue.cpp
Please check if the PR fulfills these requirements
Allow to "remove" a task from task queue.
Fix dangling ref in lambda if a Texture is deleted before data sent to gpu.
Once added task could not be removed.
Also use non naked new to for all add task and remove naked new alternative.
=> Add removeTask to taskQueue

doc/basics.md
Since we mostly have newcomers who use release-candidate, its a simple reminder to switch branch.
=> [doc] Add lines relative to branch checkout.

external/Gui/CMakeLists.txt
=> [external] Fix pass Qt version to external build.

.clang-format, .pre-commit-config.yaml, src/Core/Containers/VariableSet.hpp, src/Core/Utils/Attribs.hpp, src/Core/Utils/Singleton.hpp
Update pre-commit script and apply hook to all files
=> Pre commit update

src/Headless/CLIViewer.cpp, src/Headless/CLIViewer.hpp
Please check if the PR fulfills these requirements
Neked new is used for camera in CLI viewer, use unique_ptr instead.
Also fix 0 thread queue.
=> [headless] Fix camera possible leak.

src/Core/Asset/Camera.hpp, src/Core/Asset/GeometryData.hpp, src/Core/Asset/HandleData.hpp, src/Core/Asset/LightData.hpp, src/Core/Containers/Grid.hpp, src/Core/Containers/Tex.hpp, src/Core/Geometry/TopologicalMesh.hpp, src/Core/Geometry/TriangleMesh.hpp, src/Core/Geometry/deprecated/TopologicalMesh.cpp, src/Core/Geometry/deprecated/TopologicalMesh.hpp, src/Core/Math/DualQuaternion.hpp, src/Engine/Data/BlinnPhongMaterial.hpp, src/Engine/Data/Material.hpp, src/Engine/Data/VolumetricMaterial.hpp, src/Engine/Rendering/RenderObject.hpp, src/Engine/Scene/CameraComponent.hpp, src/Engine/Scene/DirLight.hpp, src/Engine/Scene/Entity.hpp, src/Engine/Scene/Light.hpp, src/Engine/Scene/PointLight.hpp, src/Engine/Scene/SpotLight.hpp, src/Gui/TransformEditor/TransformEditor.hpp, src/Gui/Viewer/Gizmo/Gizmo.hpp, src/Gui/Viewer/Gizmo/GizmoManager.hpp, tests/unittest/Core/topomesh.cpp
This PR remove deprecated eigen macro for aligned new.
No.
=> Remove EIGEN_MAKE_ALIGNED_OPERATOR_NEW

.github/workflows/build-matrix.yml, .github/workflows/pull-request-ci.yml, .github/workflows/push-master-ci.yml, .github/workflows/push-rc-ci.yml
Maybe this will fix codecov upload, not sure :)
=> [ci] Pass codecove token to workflow call.

external/Core/CMakeLists.txt
Previous version was using cmake 3.1, which is not supported by modern cmake versions.
Please check if the PR fulfills these requirements
- **What is the new behavior …
=> Bump nlohmann_json to 3.12.0
