STORM-IRIT/Radium-Engine

- src/Core/Containers/AlignedStdVector.hpp
- src/Core/Math/LinearAlgebra.hpp
- src/Core/Utils/File/OBJFileManager.hpp
- src/Engine/Assets/HandleData.hpp
- src/Engine/Assets/KeyFrame/KeyFrame.hpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
Depending on your compiler flags, Eigen can now require as much as 32 bytes alignment (instead of 16 previously), if you use AVX extensions. 
So it's now required to align to `EIGEN_MAX_ALIGN_BYTES` for aligned allocators.
This bugs appeared only on windows so far (probably because malloc is better behaved on Linux and we don't have AVX enabled on Linux yet.
> Fix Eigen's alignment problem with AVX

- Plugins/FancyMesh/src/FancyMeshComponent.cpp
- Plugins/FancyMesh/src/FancyMeshComponent.hpp
- src/Core/Containers/Tex3D.inl
- src/Core/Math/LinearAlgebra.hpp
- src/Core/Math/LinearAlgebra.inl
- src/Engine/Component/Component.cpp
- src/Engine/Component/Component.hpp
- src/Engine/Entity/Entity.hpp
- src/Engine/Managers/SystemDisplay/SystemDisplay.hpp
This change set has two parts.
The first two commits upgrade the raycast query which is used to query a scene from the GUI (pretty useful to get location of problematic points, vertices or triangles).
By default, the behaviour  of each component is to raycast versus all components visible render objects meshes, while it used to be only available in Fancy Mesh component.
It now  prints the intersection point in all frames of reference.
The last commit fixes a bug in the grid implementation which would happen when small negative values would be passed where 0 was expected due to floating point imprecision.
In this case the result was floored and then casted to uint which gave wrong high integer values.
The fix was to used the function `ceil()` instead of `floor()`, and add an assert to …
> Raycast & grid fix

- src/Core/String/StringUtils.cpp
- src/Engine/Assets/AssimpGeometryDataLoader.cpp
- src/Engine/Assets/AssimpWrapper.hpp
- src/Tests/CoreTests/String/StringTest.hpp
- src/Tests/CoreTests/main.cpp
This PR includes two commits :
* a unit test  for `Core::StringUtils` and a fix for the bug it helped to catch
* A fix to asset loading which would give a default name to unnamed meshes in assimp, which could cause problems for skinning setup.
> String test and asset loading fix

- Applications/MainApplication/Gui/MainWindow.cpp
This fixes a bug that happened in the following condition :
* two or more entity presents
* select an entity
* activate the gizmos
* delete the entity
This created a deadlock in the entity deletion code as the following
scenario happens:
* the entity is deleted
* it triggers its removal from the item model
* because an object was "current object" in the tree view, this triggers
the tree view to select the next object available
* this causes the gizmos to try to spawn for the new object, which
is impossible because we are in the middle of a deletion.
This problem was supposedly fixed in #153 but only incorrectly : this is
because the clearSelection() method of ItemSelectionModel clears the
'selected' items but not the 'current' items. This is fixed by the use
of clear().
> Fix gizmo deadlock

- cmake/FindRadium.cmake
Replace `${RADIUM_ROOT_DIR}/${CMAKE_BUILD_TYPE}` by `${RADIUM_BUNDLE_DIRECTORY}/`.
> Fix wrong output directory for 3rdparty

- src/Core/Math/GlmAdapters.hpp
When compiling Radium with double precision floating point, glm wrappers cause an ambiguity.
Since the RadiumToGlm wrappers are used only to set uniforms for shader programs, I just enforced them to take single precision vectors/matrices as input.
Shall we have both single and double precision versions of these wrappers?
What about the GlmToRadium wrappers (that are currently not used)?
> Fix build Radium with double precision

- src/IO/AssimpLoader/AssimpFileLoader.cpp
Due to unwanted side effect when disabling automatic triangulation in assimp loader.
Fixes #228
> Fix missing faces when loading quad meshes

- cmake/submoduleGlBinding.cmake
- cmake/submoduleGlObjects.cmake
- src/Core/File/KeyFrame/KeyFrame.hpp
- src/Core/Geometry/Partition/Partition.cpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
Correction of std::map bad allocator (KeyFrame and RenderParameters).
Correction of non efficient std::move (that prevent copy elision).
Correction of cmake scripts to detect compiler name.
> Clang compiling ... bugs in cmake scripts and some (very) strange problem with std::map allocators ... 

- Applications/MainApplication/Gui/MainWindow.cpp
- Applications/MainApplication/Gui/MainWindow.hpp
- Applications/MainApplication/Gui/ui/MainWindow.ui
- Applications/MainApplication/MainApplication.cpp
- Plugins/Animation/src/AnimationComponent.cpp
- Plugins/Animation/src/AnimationComponent.hpp
- src/Engine/Renderer/Renderer.cpp
- src/Engine/Renderer/Renderer.hpp
- src/Engine/Renderer/Renderers/ExperimentalRenderer.cpp
- src/Engine/Renderer/Renderers/ExperimentalRenderer.hpp
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
- src/Engine/Renderer/Renderers/ForwardRenderer.hpp
- src/Engine/Renderer/Texture/Texture.cpp
- src/Engine/Renderer/Texture/Texture.hpp
- src/GuiBase/SelectionManager/SelectionManager.hpp
- src/GuiBase/Viewer/Viewer.cpp
- src/GuiBase/Viewer/Viewer.hpp
- src/PluginBase/RadiumPluginInterface.hpp
PR is ready.
Adds: 
* GUI to select active renderer in Gui::MainApp
* Fallback in Gui::Viewer: when no renderer is set, use ForwardRenderer as default
* Update PluginInterface with a new handle to create renderers from plugins.
> Add support for dynamic renderer addition and swap

- Plugins/Animation/src/AnimationComponent.cpp
- src/Core/Animation/Handle/HandleWeightOperation.cpp
- src/Core/Animation/Handle/HandleWeightOperation.hpp
- src/Tests/CoreTests/Animation/AnimationTest.hpp
- src/Tests/CoreTests/main.cpp
Some models we have do not provide normalized weights.
While model files should contain normalized weights, it is safer to ensure it at load.
> Normalize skinning weights at load to ensure they sum to 1

- src/Core/Algorithm/Subdivision/FullEdgeOperation.cpp
- src/Core/Index/IndexMap.hpp
- src/Core/Index/IndexMap.inl
- src/Core/Mesh/DCEL/Dcel.cpp
- src/Core/Mesh/DCEL/Dcel.hpp
- src/Core/Mesh/DCEL/Dcel.inl
- src/Core/Mesh/DCEL/Operations/EdgeSplit.cpp
- src/Core/Mesh/Wrapper/Convert.cpp
- src/Engine/Managers/EntityManager/EntityManager.cpp
- src/Engine/Renderer/RenderObject/RenderObjectManager.cpp
- src/Tests/CoreTests/Containers/IndexMapTest.hpp
- src/Tests/CoreTests/main.cpp
The changelist you were all waiting for ! The refactor of `Core::IndexMap` as requested in issue #158.
This amazing changelist includes removal of dead code or duplicate functions. No need from the `bool`-returning `insert()` functions when the regular `insert()` function already signifies failure by returning an invalid index.
Also this changelist includes a ❤️  🏅 🍰  🦄 **unit test** 😄 🎉 🎈 🎂  ! 
Please review it with all your courage and love !
> Refactor of `Core::IndexMap`

- Applications/MainApplication/Gui/MainWindow.cpp
- Applications/MainApplication/Gui/MainWindow.hpp
- src/Engine/Renderer/Mesh/Mesh.cpp
- src/Engine/Renderer/Mesh/Mesh.hpp
- src/Engine/Renderer/Mesh/Mesh.inl
This pr includes these few changes:
- Non-const access methods of mesh data
- RM_LINE_STRIP_ADJENCY added to the supported render modes
- Textures update when changing the current renderer (Issue #247)
> Some improvements on Mesh and MainWindow

- Applications/MainApplication/Gui/MainWindow.cpp
- Applications/MainApplication/MainApplication.cpp
- src/Core/File/FileLoaderInterface.hpp
- src/Engine/RadiumEngine.cpp
- src/Engine/RadiumEngine.hpp
- src/IO/AssimpLoader/AssimpFileLoader.cpp
- src/IO/AssimpLoader/AssimpFileLoader.hpp
- src/IO/TinyPlyLoader/TinyPlyFileLoader.cpp
- src/IO/TinyPlyLoader/TinyPlyFileLoader.hpp
- src/PluginBase/RadiumPluginInterface.hpp
Small changes simplifying the addition of new loaders from plugins:
- Expose handlers in `RadiumPluginInterface`,
- Store FileLoaders using `shared_ptr`,
- In MainApp, construct the list of supported file formats from the list of registered loaders
Fixes:
- Remove unwanted explicit use of assimp in `Gui::MainWindow`, preventing to compile radium without assimp support.
> Add Loaders in plugins

- Applications/MainApplication/Gui/MainWindow.cpp
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
- src/GuiBase/Viewer/Viewer.cpp
- src/GuiBase/Viewer/Viewer.hpp
Fixes two problems:
* GL error when switching between to renderers at runtime (missing call to makeCurrent) 1672156
* Crash when starting main application:
Renderers in plugins were added while GL was not initialized.
This is fixed by allowing deferred initialization of renderers that are added before GL initialization.
> [hotfix] Renderers crash

- Applications/HelloRadium/minimalapp.cpp
- Applications/HelloRadium/minimalapp.hpp
- Applications/MainApplication/Gui/MainWindow.cpp
- Applications/MainApplication/Gui/MainWindow.hpp
- Applications/MainApplication/MainApplication.cpp
- Applications/MainApplication/MainApplication.hpp
- cmake/CompileFlags.cmake
- cmake/SubModules.cmake
- src/CMakeLists.txt
- src/GuiBase/Viewer/Viewer.cpp
- src/PluginBase/RadiumPluginInterface.hpp
- [hotfix] HelloRadium works fine now on Linux and MacOs : fix problem due to wrong order of initialisation and confusion of Qt event. Small rewrinting of the MainApplication to follow this fix. These modifications were also usefull for the introduced feature.
- [Feature] Extend the Plugin Interface to notify the plugins once OpenGL is initialised. This allow plugins to interact with the Radium OpenGl system (adding shaders, configuring the context, ...)
> [hotfix + feature] Fix Qt signaling system for OpenGL initilisation + Allow Extension of OpenGL biotope by plugins

- Applications/MainApplication/Gui/MainWindow.cpp
When loading a file with main app, just creates a new file extensions filter aggregating all the supported files formats.
> [mainapp ]Add a filter "Supported files" in the file loader dialog

- Applications/MainApplication/MainApplication.cpp
- Applications/MainApplication/MainApplication.hpp
- Applications/MainApplication/main.cpp
Add MainWindowFactory class to extend MainApplication.
MainApplication constructor take a factory to delegate the creation of MainWindow. This allows the creation of MainWindow derivate class without duplicating the MainApplication.
Next step is to provide a MainWindowInterface and move MainApplication in GuiBase.
(this PR also incorporate #277 )
> Window factory

- .travis.yml
- src/Engine/Renderer/Renderer.cpp
Just remove RM_LINES from type of geomerty that can be picked (and so remove the assert exception). 
To be fixed later.
> Do not add RM_LINES meshes to renderQueuePicking.

- Configs/alternative.xml
- Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp
- Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.hpp
- Plugins/MeshFeatureTracking/src/UI/MeshFeatureTrackingUI.cpp
- Plugins/MeshPaint/src/MeshPaintComponent.cpp
- Shaders/LinesAdjacency.geom.glsl
- Shaders/Picking.frag.glsl
- Shaders/PickingLines.geom.glsl
- Shaders/PickingLinesAdjacency.geom.glsl
- Shaders/PickingPoints.geom.glsl
- src/Engine/Entity/Entity.inl
- src/Engine/Renderer/Mesh/Mesh.cpp
- src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.cpp
- src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.hpp
- src/Engine/Renderer/Renderer.cpp
- src/Engine/Renderer/Renderer.hpp
- src/GuiBase/BaseApplication.cpp
- src/GuiBase/Utils/KeyMappingManager.cpp
- src/GuiBase/Viewer/TrackballCamera.cpp
- src/GuiBase/Viewer/Viewer.cpp
Add possibility to have modifiers on mouse buttons ;
Adapt Viewer's mousePressEvent and mouseMoveEvent accordingly ;
Fix alternative keymapping config to work on computers with pad only (e.g. mac and laptop) ;
Add a warning if an action key is bound to multiple actions ;
Add transforms management to MeshFeatureTracking ;
Add picking support for some OpenGL primitive types (see Mesh.cpp for supported types ) ;
Fixes #285
**Note**: the default configuration uses the same key for `GIZMOMANAGER_MANIPULATION`, `VIEWER_BUTTON_CAST_RAY_QUERY` and `COLORWIDGET_PRESSBUTTON` ; while the alternative configuration uses the same key for `VIEWER_BUTTON_PICKING_QUERY` and `VIEWER_BUTTON_CAST_RAY_QUERY`, and the same key for `TRACKBALLCAMERA_MANIPULATION` and `COLORWIDGET_PRESSBUTTON`.
This is currently …
> Fix Mac and laptop mouse controls

- Applications/MainApplication/Gui/MainWindow.cpp
This PR enables the loading of multiple files at once.
Currently, only one single file can be selected when opening new models.
With this change, several files can be selected and loaded at once, as if we have loaded them separately.
> Multiple file loading

- .travis.yml
- appveyor.yml
- src/GuiBase/BaseApplication.cpp
For plugins being able to take precedence over builtin loaders, when both can read the same file format, add builtin loaders after the plugins are loaded.
Bug fix.
when plugins can load the same file format than builtins laoders (eg assimp), plugins must have precedence over builtins.
assimp load all its recognize file format, even if a plugin can load the …
> Fix fileloader precedence

- Applications/MainApplication/Gui/MainWindow.cpp
When clearing the scene with a selected component, while having one of our private plugins enabled, makes the app crash.
Actually, the selection manager is told to clear its selection, then entities are destroyed. While destroying the entities', and thus their components', treeItems in the treeItemView, it somehow happens that the "currentChanged" signal of the selection manager is triggered.
This causes one of our plugins, which is connected on this signal, to crash since the "currentItem" of the selection manager isn't invalid.
Clearing the selection manager with "clear" prevents this crash (currentItem is an invalid one).
Also, it's coherent with the way we clear the selection manager when handling picking while not RO has been picked.
> Change the selection manager clear when clearing the scene ;

- Applications/MainApplication/Gui/MainWindow.cpp
- src/GuiBase/Viewer/TrackballCamera.cpp
This PR fixes these two issues : 
#327 Camera fit scene
#328 Camera reset when changing renderer
The updated position of the fitted camera does not take into account the Z-coordinate of the scene's bounding box. The camera is reset when the current renderer is changed.
The updated position of the fitted camera takes into account the …
> Camera fit

- .gitmodules
When trying to clone the submodules it appeared that the current repo for Eigen (https://github.com/RLovelett/eigen.git) was dead, so this PR replaces the reference with one to https://github.com/eigenteam/eigen-git-mirror.
> Change the Eigen ref to a working one

- src/Core/Mesh/MeshPrimitives.cpp
- src/Core/Mesh/MeshPrimitives.inl
It fixes a regression introduced in 1c4fd16567313b56286db2d0c79f5bd6ebc2c2ea. 
The `MeshUtils::makeGeodesicSphere()` method does not project vertices on the sphere.
* **Other …
> project vertices on geodesic sphere primitive

- Applications/SimpleSubdivideExample/main.cpp
- Docs/mesh.md
- Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp
- Plugins/Skinning/src/SkinningComponent.cpp
- src/Core/File/deprecated/OBJFileManager.cpp
- src/Core/File/deprecated/OFFFileManager.cpp
- src/Core/Geometry/Approximation/VariationalShapeApproximation.inl
- src/Core/Math/ColorPresets.hpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.cpp
- src/Core/Mesh/TriangleMesh.hpp
- src/Core/Mesh/TriangleMesh.inl
- src/Core/Utils/Attribs.hpp
- src/Engine/Renderer/Mesh/Mesh.cpp
- src/Engine/Renderer/Mesh/Mesh.hpp
- src/Engine/Renderer/Mesh/Mesh.inl
- src/GuiBase/Viewer/Viewer.cpp
- src/Tests/CoreTests/src/Mesh.hpp
This PR fixes #343 , which was due to non deep copy of attributes in `TriangleMesh`.
Also fixes compilation error with AppleClang due to the c++17 standard modification regarding std::random_shuffle.
No deep copy of attributes when copying a `TriangleMesh`.
No copy of attributes when copying a TriangleMesh.
Copy of needed/all attributes from …
> Fix skinning

- Applications/SimpleSubdivideExample/main.cpp
- src/Core/Algorithm/Subdivision/CatmullClarkSubdivider.cpp
- src/Core/Algorithm/Subdivision/CatmullClarkSubdivider.hpp
- src/Core/Algorithm/Subdivision/LoopSubdivider.cpp
- src/Core/Algorithm/Subdivision/LoopSubdivider.hpp
- src/Core/Algorithm/Subdivision/SubdividerUtils.hpp
- src/Core/File/deprecated/OBJFileManager.cpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.cpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.hpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.inl
- src/Core/Mesh/TriangleMesh.inl
Basic OpenMesh subdivision procedures do not deal with properties such as texture coordinates, additional normals and others.
The proposed subdivision procedures (Loop and CatmullClark schemes for now) deal with the `TopologicalMesh` properties which are stored on halfedges.
When adding new vertices, such properties are linearly interpolated along halfedges (edge mid-point) and faces (face centre).
Also, this PR fixes #349 .
* **What …
> Add attributes-aware subdivision

- Applications/HelloRadium/CMakeLists.txt
- Applications/MainApplication/CMakeLists.txt
- Applications/SimpleSubdivideExample/CMakeLists.txt
- CMakeLists.txt
- cmake/RadiumFunctions.cmake
- src/CMakeLists.txt
add a flag to use cotire (on by default)
cotire is always on 
user can disable cotire at compile time with -DRADIUM_USE_COTIRE=Off
Nope
have fun
> add a flag to use cotire (enable by default).

- src/Core/File/AssetData.hpp
- src/Core/File/CameraData.hpp
- src/Core/File/CameraData.inl
- src/Core/File/LightData.cpp
- src/Core/File/LightData.hpp
- src/Core/File/LightData.inl
- src/Engine/Managers/LightManager/LightManager.cpp
- src/IO/AssimpLoader/AssimpLightDataLoader.cpp
- [x ] The commit message follows our guidelines
- [ x] Docs have been added / updated (for bug fixes / features)
Allow the definition of area light sources in the asset that are compatible with punctual ones so that renderer that support only point light sources might use a crude approximation of area lights.
No support for area light.
Support …
> Update Light asset : add management of area light sources

- Shaders/HdrToLdr/Hdr2Ldr.frag.glsl
- Shaders/HdrToLdr/Hdr2Ldr.vert.glsl
- Shaders/Materials/BlinnPhong/BlinnPhongMaterial.glsl
- src/Engine/Renderer/RenderTechnique/ShaderProgramManager.cpp
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
- src/Engine/Renderer/Texture/Texture.cpp
- src/Engine/Renderer/Texture/TextureManager.cpp
- src/GuiBase/Viewer/CameraInterface.cpp
- src/GuiBase/Viewer/CameraInterface.hpp
- src/GuiBase/Viewer/Viewer.cpp
- src/GuiBase/Viewer/Viewer.hpp
- src/IO/AssimpLoader/AssimpGeometryDataLoader.cpp
This PR brings a correct conversion between linear RGB and sRGB color space. All the lighting computations must be done in linear RGB colorspace and the input pictures (textures) and output images (displayed or saved) are in sRGB colorspace. When loading a texture via stb_image, the conversion is requested and manage by stb. After rendering, the linear space picture is transformed to sRGB before being displayed/saved. This PR also transform the Phong shininess exponent given by …
> Add gamma correction

- .ci/compile-official-plugins.sh
- .travis.yml
Extend CI scripts to regularly test supported plugins compilation.
Plugins are packaged with Radium libraries and apps and tested alongside Radium.
The CI scripts now expect cron-type triggered builds.
When it happens, the official plugins are fetched and compiled against the current version of …
> Add support for official plugins in CI

- .ci/compile-official-plugins.sh
- src/Core/Algorithm/Subdivision/CatmullClarkSubdivider.cpp
- src/Core/Algorithm/Subdivision/CatmullClarkSubdivider.hpp
- src/Core/Algorithm/Subdivision/LoopSubdivider.cpp
- src/Core/Algorithm/Subdivision/LoopSubdivider.hpp
- src/Core/Algorithm/Subdivision/SubdividerUtils.hpp
- src/Core/File/MaterialData.hpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.cpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.hpp
- src/Core/Mesh/TopologicalTriMesh/TopologicalMesh.inl
Add subdivision operations registration and replay.
Add Attribute in TopologicalMesh for the vertex index in the input/output TriangleMesh.
Performing subdivision at each frame (e.g. after skinning) is very slow.
Performing subdivision at each frame takes 30ms on average for 2 subdivision …
> Add subdiv ops

- src/Engine/Renderer/Material/BlinnPhongMaterial.cpp
- src/Engine/Renderer/Texture/Texture.cpp
- src/Engine/Renderer/Texture/Texture.hpp
- src/Engine/Renderer/Texture/TextureManager.cpp
...is only applied on demand as its only make sense on color texture (and not on normals, roughness, ...)
Bug fix : At loading, textures where always converted to linear RGB color space by stb_loadf. This is problematic for textures, such as normals, roughness, bump, ... that do not represent colors.
Now, the conversion from sRGB to Linear RGB must be explicitely requested by the user of the texture so that noly color textures will be transforme.
* **What is the current behavior?** …
> Conversion from sRGB to Linear RGB ... 

- Plugins/Skinning/src/SkinningComponent.cpp
- src/Core/Geometry/LoopSubdivider.cpp
- src/Core/Geometry/LoopSubdivider.hpp
- src/Engine/Renderer/Mesh/Mesh.cpp
- src/GuiBase/Viewer/Gizmo/GizmoManager.cpp
Fixes 3 bugs:
- `SkinningData` clean reset
- `LoopSubdivider` default valence
- `Engine::Mesh` indices update 
- When reseting the animation, the relative poses are not reset.
- The default valence for computing weights are not enough for the Hand model.
- When adding triangles to a mesh, these are not rendered even after `setDirty(INDEX)` because the value of `m_numElements`, which is used to tell the …
> 3 bug fixes ;

- src/Core/Animation/Skeleton.cpp
- src/Core/Geometry/DistanceQueries.inl
- src/Core/Geometry/PolyLine.inl
- src/Core/Geometry/Spline.inl
- src/Core/Math/LinearAlgebra.hpp
- src/Core/Math/LinearAlgebra.inl
- src/Core/Math/Math.hpp
- src/Core/Math/Math.inl
- src/Engine/Renderer/RenderTechnique/RenderTechnique.hpp
- src/Engine/Renderer/Renderer.cpp
- src/GuiBase/Viewer/TrackballCamera.cpp
- tests/CoreTests/src/algebra.cpp
- tests/CoreTests/src/geometry.cpp
Bug fix, `clamp(T, T, T)` and Vector version clash (since there is no partial template specialisation on function).
generic clamp has been move to `Ra::Core` (instead of math).
That's dirty, but temporary, please use std::clamp instead.
"Eigen" clamp has been redesign to work with all kind of expression (I hope ;)
`Ra::Core::Math::clamp` works on scalar type, …
> Disambiguate different clamps.

- Docs/material.md
- src/GuiBase/Viewer/Viewer.cpp
default light intensity set to one
material documentation updated
docs update and default light intensity set to 1 so that default rendering is fine wrt content creation software (blender, maya, ...)
* **Other …
> Small fixes : default light intensity and material documentation

- src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp
- src/Engine/Renderer/RenderTechnique/ShaderProgram.hpp
- src/Engine/Renderer/Texture/Texture.cpp
- src/Engine/Renderer/Texture/Texture.hpp
Add methods to set VectorXi as uniforms
and to load TextureImage to GPU.
These functionality have been partially tested on my own project.
Could not send VectorXi nor TextureImage
Could send VectorXi nor TextureImage
* **Does this PR introduce a breaking change?** (What changes might users need to …
> Master v1 shaders

- Applications/MainApplication/Gui/MainWindow.cpp
- Shaders/HdrToLdr/Hdr2Ldr.frag.glsl
- src/Core/Utils/Color.hpp
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
- src/Engine/Renderer/Texture/Texture.cpp
- src/Engine/Renderer/Texture/Texture.hpp
- src/GuiBase/BaseApplication.cpp
- src/GuiBase/Viewer/Viewer.cpp
- src/GuiBase/Viewer/Viewer.hpp
This PR add two operators on Core::Utils::ColorBase to convert a color between sRGB and linear RGB color space.
This is then used, in the mainapp, to make the background color selection user friendly as, after selection, the renderer background will match exactly the chosen color.
The color chooser for the background does not show the real background color.
The background color chooser is not initialized …
> Core/Utils/Color "linear RGB" and "sRGB" conversion

- Docs/animation.md
- Plugins/Animation/src/AnimationComponent.cpp
- Plugins/Animation/src/AnimationComponent.hpp
- Plugins/Animation/src/AnimationSystem.cpp
- Plugins/Skinning/src/SkinningComponent.cpp
- Plugins/Skinning/src/SkinningComponent.hpp
- Plugins/Skinning/src/SkinningPlugin.cpp
- Plugins/Skinning/src/SkinningSystem.hpp
- src/Core/Animation/Interpolation.hpp
- src/Core/Animation/KeyFrame.hpp
- src/Core/Animation/PoseOperation.cpp
- src/Core/Animation/PoseOperation.hpp
- src/Core/Asset/HandleData.cpp
- src/Core/Asset/HandleData.hpp
- src/Core/Asset/HandleData.inl
- src/Core/Asset/HandleToSkeleton.cpp
- src/Core/Asset/HandleToSkeleton.hpp
- src/IO/AssimpLoader/AssimpHandleDataLoader.cpp
- src/IO/AssimpLoader/AssimpHandleDataLoader.hpp
This PR attempts to fix the importation of skeleton-based character animation.
**The current implementation of skinning in Radium makes it impossible to correctly load all models.
The whole skinning process needs re-implementation, but this is out of the scope of this PR.**
The current implementation has several drawbacks:
- does not handle one skeleton for …
> Fix skeleton-based character animation import

- Applications/MainApplication/Gui/MainWindow.cpp
- Applications/MainApplication/Gui/MainWindow.hpp
- Applications/MainApplication/Gui/ui/MainWindow.ui
- src/GuiBase/TreeModel/EntityTreeModel.cpp
- src/GuiBase/TreeModel/EntityTreeModel.hpp
- src/GuiBase/TreeModel/TreeModel.cpp
- src/GuiBase/TreeModel/TreeModel.hpp
This PR adds check-boxes to items in the engine object tree to toggle their visibility.
There is a 'visible' button that toggles visibility of the selected item.
Items visibility is now controlled by the check-boxes in the tree view.
If a component is unchecked, then all of its render objects are …
> Checkbox in the engine object tree for visibility

- Plugins/Skinning/src/SkinningComponent.cpp
In Debug, the skinning plugin requests data from the `ComponentMessenger` with the bad id, making the app crash.
> Fix typo making the skinning plugin crash in debug ;

- src/Core/Geometry/MeshPrimitives.cpp
- src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.cpp
- src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.hpp
First vector must be normalized to obtain good results (see "flat" Guizmo's cylinder for instance).
Bug Fix
Cylinder may be flat (for instance the TranslateGizmo has flat x and y axis).
This is due to the fact that getOrthogonalVectors wants the first argument to be normalized.
(it's already present in the doc of the function, but was not always true).
normalize vector before calling to the aformentionned function.
> Fix getOrthogonalVectors.

- CMakeLists.txt
Fix cmake when using 
RADIUM_BUILD_APPS=Off
> guard dependency in cmake by cmake option.

- src/Engine/Renderer/Camera/Camera.cpp
This PR uses core assert to check that camera is initialized before refere to it's m_RO, without this, a program that forgot to initialize the camera will segfault.
I found it usefull to use core assert, so that in release there is no performance penalities.
> Add core assert to guard Camera's m_RO access.

- Applications/HelloRadium/minimalapp.cpp
- Docs/keymapping.md
- src/GuiBase/BaseApplication.cpp
- src/GuiBase/Utils/KeyMappingManager.cpp
- src/GuiBase/Utils/KeyMappingManager.hpp
- src/GuiBase/Viewer/CameraInterface.hpp
- src/GuiBase/Viewer/Gizmo/GizmoManager.cpp
- src/GuiBase/Viewer/Gizmo/GizmoManager.hpp
- src/GuiBase/Viewer/TrackballCamera.cpp
- src/GuiBase/Viewer/TrackballCamera.hpp
- src/GuiBase/Viewer/Viewer.cpp
- src/GuiBase/Viewer/Viewer.hpp
bug fix #457
the Viewer::registerKeymapping, which should act as a call back called by keyMappingManager, add also callback's for camera and gizmo to the keyMappingManager
the PR also cleanup file management in keyMappingManager, I was not sure of the expected behavior, so I correct them to what I expect to be correct, but comment are welcoms.
an helper function of the viewer is added to register all callback's to keyMappingManager.
I don't chech minimalapp, which register camera and viewer only, it's maybe a …
> Keymapping fix

- src/Core/Geometry/Obb.hpp
- src/Engine/Renderer/RenderObject/RenderObject.cpp
- tests/unittest/CMakeLists.txt
- tests/unittest/Core/obb.cpp
Bug fix on `Aabb` with `Transforms`.
Also add a test on `Obb` in `tests/CoreTests/src/geometry.cpp`.
When applying a `Transfom` T to an `Aabb` A (basically an `Obb` - or the use made in `RenderObject`), T is applied to all the corners of A to fill an empty `Aabb`.
This becomes bad as soon as A is empty, even if T is the Identity.
A is tested before applying T. If A is …
> Fix use of transforms on aabb ;

- src/CMakeLists.txt
Feature Fix ;)
The DEBUG definition is not exported when the lib is compiled in debug mode.
So MACROs such as GL_ASSERT are empty.
The DEBUG definition is exported, and so the MACROs.
> Add missing definition for debug mode

- src/GuiBase/Viewer/TrackballCameraManipulator.cpp
Fix trackball issue when updating `phi` / `theta` angles from Y-axis aligned direction.
- When such a case occurs, the `phi` angle is automatically set to `0`, whatever the orientation of the camera, which is not right.
- There is also an issue with the `theta` angle, which is set to `acos( Dir.y() )`, which makes it `-Pi` above, and `Pi` below, which is reversed from the computations made when rotating the camera.
* **What is …
> Fix trackball when setting camera direction along Y axis ;

- src/GuiBase/Viewer/Viewer.cpp
Bug fix
firsts draws raise a warning `QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined`
Test if viewer is exposed before swap
no
> Viewer: check isExposed before swap.

- src/GuiBase/BaseApplication.cpp
- src/GuiBase/BaseApplication.hpp
see https://doc.qt.io/qt-5/qapplication.html
"Warning: The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string."
Bug fix
main-app, and all other BaseApplications, (segfault somtimes ...) 
Fixed, 
But still need deferred opengl initialization (I will open an issue on that).
* **Does this PR introduce a breaking change?** (What changes might users need to make in …
> BaseApplication: qt need a reference to argc !

- src/Engine/Renderer/Renderer.cpp
…on default framebuffers
Application crashes when used with a single-buffered default framebuffer. 
Application will no crash and keep the default framebuffer with its default configuration according to the openGL Spec.
>  No need to set draw or read buffers …, fix #504

- src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.inl
This PR add basic functionalities to allow material parameters inspection.
This is a first sketch that allow to develop scene exporters. 
See the GLTF2.0 private plugin for a usage example.
> Allow read-Only access to Shader renderParameter.

- cmake/filelistEngine.cmake
- src/Engine/Renderer/Material/Material.cpp
- src/Engine/Renderer/Material/Material.hpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.cpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
- src/Engine/Renderer/RenderTechnique/RenderTechnique.cpp
- src/Engine/Renderer/RenderTechnique/RenderTechnique.hpp
- src/Engine/Renderer/RenderTechnique/RenderTechnique.inl
This is related to issue/feature request #518 and must come after PR #520.
This PR allow to add  several `#define PROPERTY` to a shader configuration from a ShaderParameterProvide when the provider is associated to a pass.
This PR must be discussed to study its extensibility to other source elements (#include, snippets, ...)
> Shader parameter provider can add #define to the shader

- src/GuiBase/Utils/KeyMappingManager.cpp
Restrict use of Qstring::chopped if Qt version is more than 5.10
bug fix
Compilation fails if compiled with qt < 5.10, due to call to `QString::chopped` (introduced in Qt 5.10)
https://doc.qt.io/qt-5/qstring.html#chopped
Use `QString::chop` for old versions of Qt.
> Fix compilation error with Qt version < 5.10.0

- src/GuiBase/BaseApplication.cpp
- src/PluginBase/pluginMetaDataDebug.json
- src/PluginBase/pluginMetaDataRelease.json
Allow to load plugins even if there are non-plugin dynamic libraries in the searched directories.
When a directory searched by BaseApplication when loading plugins contains dynamic libraries that are not Radium Plugin, the application stops with an error message. This prevent storing plugins and their dependences in the same directory.
When a dynamic library that is …
> Skip non-plugin dynamic libraries when loading plugins.

- cmake/Config.cmake.in
Fix issue #533 
CMake package forces the dependency with OpenMP, which makes it unusable when not available. 
Export dependency only when OpenMP is used when compiling Radium
> [cmake] Export dependency to OpenMP only when required

- src/Engine/Component/GeometryComponent.cpp
- src/Engine/Component/GeometryComponent.hpp
resolves #536 
Store the local transformation matrix of a geometric component into the associated renderobject instead of applying the transformation once at load-time.
See issue #536
Mesh (and point cloud) are not transformed once. The transformation matrix of the associated renderObject store now the mesh local transformation.
> Fix Mesh pre-transform problem.

- src/Core/external/CMakeLists.txt
- src/IO/external/CMakeLists.txt
Closes #538 closes #526 
*please test if all functionalities are presents*
From the original PR
I tried loading some animated models to check the skinning plugin is working.
Actually it is not working well with the current version of assimp (the skeleton animation seems broken) so I propose to stick with the last release tag until we fix this. 
Thus we can advance on more urgent stuff.
bug fix, explicit tags for all external project
here is what is set:
```bash
$ find . -path \*external/CMakeLists.txt -exec grep -B2 -H GIT_TAG {} \;
./src/Core/external/CMakeLists.txt-ExternalProject_Add(Eigen3
./src/Core/external/CMakeLists.txt-    GIT_REPOSITORY …
```
> cmake: explicit tags, fix #526

- src/GuiBase/BaseApplication.cpp
This PR propose less disturbing messages when loading plugins.
Less disturbing messages when loading plugins (No error message  are printed when there is no error!)
If there is no plugin installed in the default plugin directory, the current base application print an error messages even if this is not an error.
Error messages are limited to real error at plugin loading and if no plugin is found in the default directory, only a debug message is logged.
for user specified directory, informational messages are …
> Cleaner plugin loading error and debug messages

- src/Engine/Renderer/RenderTechnique/RenderParameters.cpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
- src/Engine/Renderer/RenderTechnique/RenderParameters.inl
Buf fix
There is also one feature which give access to renderparameters non const, so one can add directly parameters by name, without having to pass thru specific material implementation. This feature can be postpone if needed.
A const char* ptr is passed to and stored in, RenderParameter.
But there is nothing that guarantees this ptr is valid during the whole program execution.
Use const std::string instead. I have changed all the call, but I think only the …
> [engine] use string instead of char*

- src/Core/Geometry/TopologicalMesh.inl
Alow to compile topomesh with older version than on CI of compiler
Compilation fix
error on non-instanciated template method returning ref to temporary
the template method compile and rais a static_assert if instantiated with an unsupported type.
> Fix topomesh compilation issue.

- Shaders/Materials/BlinnPhong/BlinnPhong.glsl
- Shaders/Materials/BlinnPhong/BlinnPhongZPrepass.frag.glsl
- Shaders/Materials/Lambertian/Lambertian.glsl
- Shaders/Materials/Lambertian/LambertianZPrepass.frag.glsl
- Shaders/Materials/Plain/Plain.glsl
- cmake/filelistEngine.cmake
- doc/developer/material.md
- src/Engine/Renderer/Material/BlinnPhongMaterial.cpp
This PR define a GLSL interface to access the emissivity of a surfacic material.
For now, emissive materials are not supported in Radium and there is a need, when compositing shaders, to access the individual components of a material : microgeometry, BSDF (that are already managed by the GLSL interface of Materials) and emissivity.
This PR just add the definition of the interface in the documentation and implement this interface in BlinnPhong and Lambertian GLSL implementation. (For now, these materials can't be emissive so the function returns …
> Add a way to access to the emissivity of a material.

- CMakeLists.txt
- cmake/externalFunc.cmake
- src/Core/Animation/KeyFramedValueInterpolators.hpp
- src/Core/external/CMakeLists.txt
- src/Engine/external/CMakeLists.txt
- tests/unittest/Core/animation.cpp
1. acabddf  CMake bug fix: allow consecutive external updates
2. d7896df CMake new functionality: automatically reinstall externals when moving the installation dir
3. 12df1c5 and 093cc85 Cleaning: remove dead code in CMake and compilation warnings
1. Unskipping external compilation for `Core` and `Engine` might fail during the patch step for cpplocate, glbinding and globject.
2. Changing the `CMAKE_INSTALL_DIR` for an already configured radium project might fail at …
> Reinstall external when moving install + fix external updates

- src/CMakeLists.txt
Hotfix
Windeployqt is not installed, which breaks the cmake package on windows.
On this build (https://github.com/STORM-IRIT/Radium-Releases/runs/898362991?check_suite_focus=true), the applications cannot be generated because the file is missing
Add proper installation directives for Windeployqt.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …
> [hotfix] Add missing install directive for Windeployqt.cmake

- cmake/radium_setup_functions.cmake
Add missing Qt internal plugin on MacOs (Qt Platform Abstraction, MacStyle)
* **What kind of change does this PR introduce?** (Bug fix, feature, …
> Add missing commit of PR #591

- Shaders/Materials/BlinnPhong/BlinnPhong.frag.glsl
- Shaders/Materials/Lambertian/Lambertian.frag.glsl
- Shaders/Points/PointCloud.geom.glsl
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
Fix shading computation when rendering point clouds
* **What …
> Fix point cloud rendering

- Shaders/Materials/BlinnPhong/BlinnPhong.glsl
- Shaders/Materials/BlinnPhong/BlinnPhongZPrepass.frag.glsl
- Shaders/Materials/Lambertian/Lambertian.glsl
- Shaders/Materials/Plain/Plain.glsl
- doc/developer/material.md
This PR introduce separable BSDF interface in the GLSL …
> Add separable BSDF interface to materials.

- src/Engine/System/System.hpp
Add a public method to the base class System so that directly …
> Allow component registration into a system from outside the system.

- Shaders/Materials/Lambertian/Lambertian.glsl
- Shaders/Materials/Plain/Plain.glsl
Bugfix
The implementation of `getGGXRoughness` returns `int` for some materials. The function is expected to return `float`, which create compilation errors on some systems (e.g. ubuntu 18.04. with Intel GPU).
`getGGXRoughness` implementations return `float` values.
No
* **Other …
> [GLSL] Fix implicit cast

- Shaders/Points/PointCloud.geom.glsl
- src/Engine/Component/GeometryComponent.hpp
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
- tests/ExampleApps/SimpleSimulationApp/main.cpp
Draft PR to discuss how to allow renderObjects/Component to define some specific rendertechnique part.
For now, when building the rendertechniques, forward renderer make explicitely check for point clouds and add a geometry shader (already in the master branch) and setup a specific shaderParameterProvider (new in this branch).
We must discuss how to make this fully general so that renderObject (and thus components that generates those renderobjects) ca add specific things to any render technique
- Check with the script provided in …
> Point cloud parameter provider

- external/Engine/CMakeLists.txt
- external/Engine/package.cmake
Closes #584 
The issue was due to wrong `external_DIR` variable values for glm, glbinding and globjects.
as the variables are set in two different files, there was some errors not detected by the CI nor our tests : 
- `external/Engine/CMakeLists.txt` has errors in its paths but is used only to configure/build/install dependencies. These errors were at the origin of the issue.
- `external/Engine/package.cmake` was correct and used by other Radium component so that the issue was hard to identify.
This PR set the right paths and try to set the paths as simple as possible and add a WARNING comment at the beginning of the `external/Engine/package.cmake` to prevent future errors.
> fix issue #584

- doc/developer/buildchain.md
- external/CMakeLists.txt
- scripts/list_dep.py
Impove and clarify doc.
If one try to compile/install external once for all in a subdir of radium engine, radium configure fail.
The doc state that one have to compile/install external in a directory outside radium source.
> [doc] update external build doc.

- cmake/Config.cmake.in
This PR fix a typo in tinyply directory name that prevent configuration of Radium_based applications when externals are embeded in the Radium bundle
> Fix typo in tinyply dir name

- cmake/filelistEngine.cmake
- src/Engine/Renderer/Material/Material.hpp
- src/Engine/Renderer/Material/Material.inl
- src/Engine/Renderer/Material/RawShaderMaterial.cpp
- src/Engine/Renderer/Material/RawShaderMaterial.hpp
- src/Engine/Renderer/Material/RawShaderMaterial.inl
- src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
- src/Engine/Renderer/RenderTechnique/ShaderConfigFactory.cpp
- src/Engine/Renderer/RenderTechnique/ShaderConfigFactory.hpp
- tests/ExampleApps/CMakeLists.txt
- tests/ExampleApps/RawShaderMaterial/main.cpp
This PR add a new type of Material to the render Engine to compute the appearance of a geometry.
It also add an example application  to demonstrate and test of the new functionality.
The added `RawShaderMaterial` class allows to define the `Material` associated to a `RenderObject` by giving explicitely a set of shaders and the associated parameterProvider. 
Shader source code is instance specific and can be changed dynamically. 
Such a `Material` does not necessarily implement the GLS BSDF interface. As a consequence, this `RawShaderMaterial` is …
> Definition of a Material from raw shaders set and an associated parameterProvider

- src/GuiBase/Viewer/FlightCameraManipulator.hpp
- src/GuiBase/Viewer/TrackballCameraManipulator.hpp
Small change in camera manipulators API
* **What is the …
> Expose manipulator keys (protected)

- cmake/filelistCore.cmake
- src/Core/Utils/StackTrace.cpp
- src/Core/Utils/StackTrace.hpp
- src/Engine/Renderer/Mesh/Mesh.hpp
- src/Engine/Renderer/OpenGL/OpenGL.hpp
- src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp
This PR add only a `Ra::Core::Utils` fonction to display the execution stack and to ease self debugging. This function is called, e.g. by the macro `GL_CHECK_ERROR` in debug mode to ease locating in which call sequence an OpenGL error is thrown.
> Add self debugging function StackTrace and better Debug messages

- .github/workflows/deploy-doc.yml
- doc/main.md
Add a github workflow to generate doxygen documentation and push to gh-pages, when new pushes are added to master.
gh-pages were generated by travis, not updated since we do not use travis anymore
Now the doc is updated. I have removed two badges which were filtered by github pages and produce ugly output.
no
tested on my own repo to check if deploy works... it …
> [github] deploy doc

- doc/CMakeLists.txt
* **What kind of change does this PR introduce?** 
bug fix
* **What is the current behavior?**
github workflow use doc/CMakeLists.txt as a standalone project, but some cmake variables are then not set.
For instance there is no sources files listed when generating the doc, so no documentation for the classes ;)
(re-)define virables in the doc/CMakeLists.txt, so the documentation can be generated as a standalone cmake project.
no
I focus on documentation pages in the previous PRs, and just realize "something" is missing.
> [cmake] make doc CMakeLists.txt working standalone.

- cmake/externalFunc.cmake
- src/Engine/CMakeLists.txt
- tests/CMakeLists.txt
HOT FIX 
#644 introduce a fix for windows compilation with pre built externals, but breaks configure time built externals.
This hot fix checks if externals *_DIR is define before trying to find externals. If such *_DIR cmake variable is not defined, it means that build needs to find them in build dir, and their setup is done along with Radium libs.
> Fix windows external

- cmake/Config.cmake.in
> [Hotfix] Load radium_setup_functions at the beginning

- src/Core/CoreMacros.hpp
Disable compiler warning with MSVC.
* **What is the current …
> Disable warning C4275 with MSVC

- cmake/radium_setup_functions.cmake
- src/Core/Resources/Resources.cpp
On windows, when installing an app outside of the Radium bundle, install also the Radium resources (shaders, ...).
> Fix Radium resources for app install on windows

- src/Core/Geometry/TopologicalMesh.cpp
- src/Core/Geometry/TopologicalMesh.hpp
- tests/unittest/Core/topomesh.cpp
Bug fix.
When a TopologicalMesh is create with the initWithWedge method, face indices are broken
This patch is a hot fix, adapted from some part of #589, but a bit differently. 
After merge, take care when rebasing #589 to have the new version (since the initWithWedge method move from cpp to inl, it will not be automatic).
> Fix topo init

- .github/workflows/pull-request-ci.yml
according to https://github.com/jurplel/install-qt-action/commit/49465b8677c54237625d80d9294b4c42fa43a645#commitcomment-46393956
mirror option is not needed nor supported anymore.
> [github] remove mirror options.

- cmake/radium_setup_functions.cmake
- doc/concepts/plantUML/initEngineGL-polymorphic.puml
- src/Engine/RadiumEngine.cpp
- src/Engine/RadiumEngine.hpp
- src/Engine/Renderer/Material/BlinnPhongMaterial.cpp
- src/Engine/Renderer/Material/LambertianMaterial.cpp
- src/Engine/Renderer/Material/PlainMaterial.cpp
- src/Engine/Renderer/Material/VolumetricMaterial.cpp
- src/Engine/Renderer/RenderTechnique/RenderTechnique.cpp
- src/Engine/Renderer/RenderTechnique/ShaderConfiguration.cpp
- src/Engine/Renderer/RenderTechnique/ShaderProgramManager.cpp
- src/Engine/Renderer/RenderTechnique/ShaderProgramManager.hpp
- src/Engine/Renderer/Renderer.cpp
- src/Engine/Renderer/Renderer.hpp
- src/Engine/Renderer/Renderers/DebugRender.cpp
- src/Engine/Renderer/Renderers/ForwardRenderer.cpp
- src/GuiBase/BaseApplication.cpp
- src/GuiBase/BaseApplication.hpp
- src/GuiBase/MainWindowInterface.hpp
- src/GuiBase/RadiumWindow/SimpleWindow.cpp
- src/GuiBase/RadiumWindow/SimpleWindow.hpp
- src/GuiBase/Viewer/Viewer.cpp
- src/GuiBase/Viewer/Viewer.hpp
- src/GuiBase/Viewer/WindowQt.hpp
- tests/ExampleApps/CustomCameraManipulator/main.cpp
- tests/ExampleApps/DrawPrimitivesApp/minimalapp.cpp
- tests/ExampleApps/HelloRadium/main.cpp
- tests/ExampleApps/RawShaderMaterial/main.cpp
- tests/ExampleApps/SimpleAnimationApp/main.cpp
- tests/ExampleApps/SimpleSimulationApp/main.cpp
Closes #670 
To test this proposal using Radium-Apps, pull the branch engine_init_3steps from STORM-IRIT/Radium-Apps repo
Apps_examples from this repo works with this proposal.
The only modifications needed by an application relying on Ra::Gui::BaseApplication to use this proposal is just to modify the application creation code.
instead of 
```c++ 
Ra::GuiBase::BaseApplication app( argc, argv, YourWindowFactory {} );
```
do 
```c++ 
Ra::GuiBase::BaseApplication app( argc, argv );
app.initialize( YourWindowFactory {} );
```
Before this PR, engine initialization and BaseApplication initialization where monolithic. This prevented to customize the engine parametrization from an app derived from BaseApplication so that one can add specific services and manage coherently its custom application …
> Engine init 3steps

- cmake/ExternalInclude.cmake
- external/Core/CMakeLists.txt
- external/Engine/CMakeLists.txt
- external/IO/CMakeLists.txt
bugfix
Radium does not require `git`, while it is a mandatory requirement to fetch the externals.
Check with cmake that `git` package is available.
No change 
> Request for git when fetching externals

- .github/workflows/pull-request-ci.yml
feature for github action pull-request-ci
our usage of cache for qt install was not good (using relative path do not work with cache@v2).
so we removed cache for qt 
after a [discussion](https://github.com/jurplel/install-qt-action/issues/51) on install-qt they point out to use cache@v1.
let's give it a try.
> [github] Qt cache use cache@v1 (v2 is not compatible).

- doc/developer/mesh.md
- src/Core/Geometry/TopologicalMesh.cpp
- src/Core/Geometry/TopologicalMesh.hpp
- src/Core/Geometry/TopologicalMesh.inl
- tests/unittest/Core/topomesh.cpp
A bug fix: always add wedge property to topo mesh, even if create on its own. fixes #693
Also adds the mergeEqualWedge method to "compact" a topo mesh if different wedges end up with the same values.
If a topo mesh is create empty, without a core mesh as reference, wedge property is not initialized, so some function (e.g. delete_face) core asserts.
warning message is printed if a face is deleted and have invalid wedge indices.
* **Does this PR introduce a breaking change?** (What changes might users need to …
> Topo wedges

- src/Engine/Data/RawShaderMaterial.cpp
- src/Engine/Data/RawShaderMaterial.hpp
- tests/integration/CMakeLists.txt
Fix #694
Bug fix, when moving and replacing namespace, something bad happens ...
Even if the converter/material/naming need refactoring, this PR fix the issue.
Remove integration target from install
RawShaderMaterial converter is registered with a inconsistant name regarding RawShaderMaterialData.
tests/ExampleApps/RawShaderMaterial crashes
The names are consistent, the app do not crash
> fix #694: RawShaderMaterial naming convention, and integration target

- doc/basics/compilation.md
- doc/basics/radium-as-submodule.md
- doc/concepts/plantUML/initEngineGL-polymorphic.puml
- doc/developer/buildchain.md
- doc/developer/cameraManipulator.md
- doc/developer/featurepicking.md
- doc/developer/keymapping.md
- doc/developer/oldmanual.md
- doc/developer/plugin.md
- doc/developer/timeline.md
- src/Core/Geometry/TopologicalMesh.cpp
- src/Core/Geometry/TopologicalMesh.inl
- src/Core/Tasks/TaskQueue.cpp
- src/Core/Utils/Index.hpp
- src/Core/Utils/Index.inl
- src/Engine/Rendering/RenderTechnique.hpp
- tests/unittest/Core/indexmap.cpp
Feature: add cast constructor to Index, to avoid static cast
Index takes only int (aka Index::IntegerType) other type may need static cast
Fix #666
Now one can construct an index from unsigned int, long int, and unsigned long int without casts.
If the value is more than int limit, an invalid index is built.
> Add other interger ctor to Index. Fix #666

- src/Engine/RadiumEngine.hpp
- src/Gui/Viewer/Viewer.cpp
- src/Gui/Viewer/Viewer.hpp
- src/IO/deprecated/FileManager.hpp
- src/IO/deprecated/OBJFileManager.hpp
- src/IO/deprecated/OFFFileManager.hpp
Remove [[deprecated]] tag when no alternative is already given.
Warnings are printed when using deprecated feature, but there is no alternative, so it's not already deprecated.
Fix #701 
no warnings
> [core][gui] remove not so deprecated deprecated tags

- cmake/radium_setup_functions.cmake
- src/Engine/Rendering/ForwardRenderer.cpp
Here is two small fixes
The first one is on the cmake side
the modification add quotes around one variable where I had some issue when there is two much files in the shader list (I got an error at config time wrong number of parameter)
Other variables deserve quotes, but it's another history.
The second one is in ForwardRenderer, the hack about point clouds adds a geomShader even if the geometry is not a point cloud.
It creates problems with any faceless renderered geometry.
> Small fixes

- tests/unittest/Gui/keymapping.cpp
Bug fix, QSettings ctor do not store it's org and app string globally, but we need that for testing.
So this PR adds the call to static method  `QCoreApplication::setOrganizationName` and `QCoreApplication::setApplicationName`
for KeyMappingManager's unit tests.
(previous behavior is tests may fail if you have stored a default setting for your application, and pass otherwise, now it pass everytime).
> [tests] Store QSettings org and app name globally.

- src/Engine/Rendering/Renderer.cpp
Only 1 macro called at a place where it is not needed !
This PR allow to instantiate Renderers before any openGL context is bound. This allow to implement and used dynamically configurable renderers.
> Removed some superfluous (and very restricting) code.

- src/Engine/Scene/SystemDisplay.hpp
Fix the namespace in the RA_DISPLAY_* macros.
Also add the …
> Fix namespace for debug display macros ;

- src/Gui/BaseApplication.cpp
- src/Gui/MainWindowInterface.hpp
- src/Gui/RadiumWindow/SimpleWindow.cpp
- src/Gui/RadiumWindow/SimpleWindow.hpp
- src/Gui/Viewer/Viewer.cpp
- src/Gui/Viewer/Viewer.hpp
- tests/ExampleApps/CustomCameraManipulator/main.cpp
- tests/ExampleApps/DrawPrimitivesApp/main.cpp
- tests/ExampleApps/DrawPrimitivesApp/minimalradium.cpp
- tests/ExampleApps/HelloRadium/main.cpp
- tests/ExampleApps/RawShaderMaterial/main.cpp
- tests/ExampleApps/SimpleAnimationApp/main.cpp
- tests/ExampleApps/SimpleSimulationApp/main.cpp
In all the demo applications and Radium apps (PR associated), the method `MainWindowInterface::postLoadFile()` was called each time a scene is set. As the role of this method was not so clear when a scene is built from scratch (without loading a file), This PR rename this function as `MainWindowInterface::prepareDisplay()` and clarifies its reference documentation.
To be more convenient, a new method was added to the `Gui::Viewer` class to prepare the viewer to display a scene and this method is called by `MainWindowInterface::prepareDisplay()` for `Gui::BaseApplication` derived apps.
For other apps, i.e. DrawPrimitiveDemo, this method could be called directly to allow scene creation in a renderer independant way.
Updated packages : 
- Gui : `MainWindowInterface` and `Viewer`
- test : all …
> Make scene display setting more clear and usable - update drawPrimitive Demo

- tests/ExampleApps/DrawPrimitivesApp/minimalradium.cpp
Bugfix
MinimalApp does not compile without assimp
Protect assimp code: Radium logo is disabled when compiling without assimp.
nop
> [apps] Fix minimal radium when not using assimp

- src/Engine/Rendering/ForwardRenderer.cpp
Closes #725 
Forward Renderer needs that a material is associated to each RenderObject to build its RenderTechnique. 
Now, adding default red lambertian material on objects that haven't one and display a warning.
> Fix issue 725

- src/Gui/Viewer/Gizmo/GizmoManager.hpp
In the file Gui/Viewer/Gizmo/GizmoManager.hpp the struct ItemEntry is predeclared in the namespace Ra::Engine whereas it must be predeclared in the namespace Ra::Engine::Scene
This wrong predeclaration make compilation failed for client lib or app that include both  GizmoManager.hpp and ItemEntry.hpp
This PR fix this by predeclaring the struct ItemEntry in the right namespace in the file Gui/Viewer/Gizmo/GizmoManager.hpp
> GizmoManager predefine the struct ItemEntry in the wrong namespace

- src/Engine/RadiumEngine.cpp
- src/Engine/RadiumEngine.hpp
Since stbi loader do not align pixels.
Should be converted to 4 byte alignment by the driver and do not impact performance.
[doc](https://www.khronos.org/opengl/wiki/Common_Mistakes)
[discussion](https://stackoverflow.com/questions/11042027/glpixelstoreigl-unpack-alignment-1-disadvantages)
Fixes #549
See #549 
Correct display of non multiple of 4 pixels widths.
Nope.
> [engine] add opengl state, and set unpack alignment to 1.

- src/Gui/BaseApplication.cpp
Feature
Radium BaseApplication stops when parsing command line with unknown parameters
Print a warning and continue to start the application
Nop
> [Gui] do not fail when command line parsing fails

- src/Engine/RadiumEngine.cpp
closes #738 
If Radium Resources are not found, do not exit from the application but set the resources path to the current directory.
> Fix issue #738 (regression)

- cmake/Config.cmake.in
- doc/basics/radium-as-submodule.md
- doc/developer/cmakeutilities.md
This PR add properties on the Radium::IO exported target
Applications outside of the Radium source tree can't request for support of assimp or tinyply loaders.
The properties `RADIUM_IO_USE_ASSIMP` and `RADIUM_IO_USE_TINYPLY` are added to the target Radium::IO to allow client applications, library or plugins to tests for support, respectvely, of the assimp or tinyply file loaders
* **Does this PR introduce a …
> Export io properties

- cmake/radium_setup_functions.cmake
Fix typo in the call to install_plugin_resources in `radium_setup_functions.cmake`
> [cmake] fix typo in cmake function call

- src/Core/Animation/KeyFramedValue.hpp
bug fix
insert a key frame in front crash on windows in debug, which check iterator decrement before "begin".
so decrement iterator only if it's define.
> Fix keyframedvalue

- src/Core/Animation/DualQuaternionSkinning.cpp
- src/Core/Animation/DualQuaternionSkinning.hpp
Add missing `const` to reference to vertices parameter of …
> [core] Add missing const in Dual Quaternion skinning.

- src/IO/AssimpLoader/AssimpLightDataLoader.cpp
PR #766 introduce a bug in assimp loader, where position where loaded as direction.
Here is a fix.
> [io] Fix assimp loading point homogeneous coordinates.

- src/Gui/Viewer/CameraManipulator.cpp
- src/Gui/Viewer/CameraManipulator.hpp
- src/Gui/Viewer/Gizmo/Gizmo.hpp
> [gui] remove pre-declaration of Camera in the wrong namespace.

- .github/workflows/push-master-ci.yml
Run full ci matrix on branch release-candidate, without updating badges.
> [github] also run full configs on release-candidate

- src/Core/Geometry/IndexedGeometry.inl
> [core] detach observers on MultiIndexedGeometry before deletion.

- src/Engine/Rendering/ForwardRenderer.cpp
This PR add wireframe rendering for transparent objects.
When rendering in wireframe, only opaque objets are drawn
opaque and transparent objects are drawn in wireframe mode
no
> Wireframe on transparent

- .clang-format
- src/Engine/Data/Texture.hpp
- src/Engine/Rendering/Renderer.cpp
- src/Engine/Rendering/Renderer.hpp
- src/Gui/Viewer/FlightCameraManipulator.cpp
- src/Gui/Viewer/Gizmo/GizmoManager.cpp
- src/Gui/Viewer/TrackballCameraManipulator.cpp
- src/Gui/Viewer/Viewer.cpp
- src/Gui/Viewer/Viewer.hpp
- src/Gui/Viewer/WindowQt.cpp
- src/Gui/Viewer/WindowQt.hpp
This PR change the OpenGL initialization procedure in the Viewer class so that, as soon as the OpenGL context is available, the OpenGL subsystem is marked as initialized. Doing that, all client applications/libraries/plugin, notified during the initialization process can use any operation requesting The OpenGL context to be bounded. 
This PR also fix a makecurrent/donecurrent problem when some methods are called with the OpenGL context bound while this method assume it should be not.
> OpenGL initialization of Viewer

- external/CMakeLists.txt
Bugfix (kind of)
It is currently possible to compile externals with an unsupported compiler.
Check compiler version in 'external/cmake'
No change required downstream
> Check compiler version in external/cmake

- src/Gui/Viewer/RotateAroundCameraManipulator.cpp
- src/Gui/Viewer/RotateAroundCameraManipulator.hpp
- src/Gui/Viewer/TrackballCameraManipulator.cpp
- src/Gui/Viewer/TrackballCameraManipulator.hpp
- src/Gui/Viewer/Viewer.cpp
- tests/ExampleApps/CustomCameraManipulator/main.cpp
- tests/ExampleApps/DrawPrimitivesApp/main.cpp
Bug fix, gizmo should change color on hover, but this was not the case (don't know when it was introduced ...)
Gizmo do not change color on hover, this is due to the "camera mapping" which is by default "invalid" in CameraManipulator class, and was not overridden.
Selected gizmo "axe" change color on hover, prior to click.
Also rename some in class using, which should change client code, to use a consistant naming.
> Fix gizmo hover

- src/Gui/Viewer/RotateAroundCameraManipulator.cpp
- src/Gui/Viewer/RotateAroundCameraManipulator.hpp
Bug fix
RotateAroundCameraManipulator "jumps" on first mouse move due to bug in prev/last mouse coordinates.
This was not the case before since there was a bug on camera key mapping context that do not trigger mouse press.
Fixed
> Fix rotate cam

- src/Core/Asset/GeometryData.cpp
- src/Core/Asset/GeometryData.hpp
- src/Core/Asset/GeometryData.inl
- src/Engine/Data/Mesh.hpp
- src/Engine/Scene/GeometryComponent.cpp
- src/IO/TinyPlyLoader/TinyPlyFileLoader.cpp
Remove deprecated code
Loaders use deprecated attribute m_color in `Asset::GeometryData`.
Remove this deprecated attribute and update Tinyply loader to set attributes directly
Other loaders using this attribute will have to be updated to use the attribmanager.
Other deprecated attributes will have to be cleaned the same way, but this can be done in another PR.
> [io] Remove deprecated attribute color in GeometryData

- tests/ExampleApps/HeadlessLibAndApp/libHeadless/CMakeLists.txt
- tests/ExampleApps/HeadlessLibAndApp/libHeadless/Config.cmake.in
This PR make the RadiumHeadless demon library to be usable by any external client application by doing a simple `find_package(RadiumHeadless REQUIRED)`
This PR also fix RadiumHeadless missing header in the installed Bundle.
To use the Radium headless facilities, one have to do two things : 
- `find_package(Radium REQUIRED COMPONENTS ...)` with the right set of components to access Radium base libs
- `find_package(Headless)` to …
> Fix headlesss install

- Shaders/Picking/PickingPoints.geom.glsl
- src/Engine/Rendering/Renderer.cpp
This is a quick fix for issue #837.
Point cloud are now easily pickable.
resolve #837.
> temporary fix (because it's an hack) of issue #837

- scripts/is-history-pr-compatible.sh
CI script refer to master instead of release-candidate branch.
This PR fix the typo.
> [script] update message according to release-candidate

- src/Gui/Viewer/Viewer.cpp
- src/Gui/Viewer/Viewer.hpp
Feature
Mouse events are handled by the viewer and its inheriting classes
Mouse events are propagated through QT signals, which allows to use them in plugins
No
> [Gui] Propage Mouse events using Qt signals

- tests/unittest/IO/volumeloader.cpp
Increase epsilon booster so that io tests work with Scalar=double, while the reader and stored data are floats.
> [tests] fix #855 epsilon so that io test work with double

- cmake/CompilerOptions.cmake
- external/CMakeLists.txt
- external/Core/CMakeLists.txt
Bug fix
When building the externals automatically at configure time on some platform, cmake throws an error on its doc target:
```
CMake Error at doc/examples/CMakeLists.txt:5 (add_executable):
CXX_STANDARD is set to invalid value ''
```
Things that have been tested (do not directly fix, but somehow try to circumvent the problem):
- the eigen buildchain is disabled for the documentation target,
- Eigen has been …
> Fix configuration error with built-in externals

- .cmake-format
- .github/workflows/pull-request-ci.yml
- cmake/Config.cmake.in
- cmake/QtFunctions.cmake
- cmake/RadiumSetupFunctions.cmake
- cmake/Windeployqt.cmake
- doc/basics/compilation.md
- doc/basics/dependencies.md
- doc/basics/troubleshooting.md
- doc/developer/plugin.md
- src/CMakeLists.txt
- src/Gui/CMakeLists.txt
- src/Gui/Timeline/Timeline.cpp
- src/Gui/Utils/KeyMappingManager.cpp
- src/PluginBase/CMakeLists.txt
- tests/ExampleApps/CMakeLists.txt
- tests/ExampleApps/EntityAnimationDemo/CMakeLists.txt
- tests/ExampleApps/KeyEventDemoApp/CMakeLists.txt
- tests/ExampleApps/PickingDemoApp/CMakeLists.txt
- tests/ExampleApps/VolumeDemoApp/CMakeLists.txt
- tests/ExamplePluginWithLib/Downstream/CMakeLists.txt
- tests/ExamplePluginWithLib/Downstream/Plugin/CMakeLists.txt
- tests/ExamplePluginWithLib/Downstream/README.md
- tests/ExamplePluginWithLib/Upstream/Plugin/CMakeLists.txt
- tests/integration/CMakeLists.txt
- tests/unittest/CMakeLists.txt
Feature
Radium can only be compiled using Qt5.
Radium can now be compiled and deployed using either Qt5 or Qt6.
Yes: Qt is linked against versionless targets, so client applications might also need to do it.
> Add support to Qt6

- src/Gui/Timeline/Timeline.cpp
- src/Gui/Timeline/Timeline.hpp
Only rename a slot connected automatically by name to a Qt signal.
The actual version connect to a deprecated signal in Qt5 that is removed from Qt6. If this does not prevent to compile, there is a Qt warning at runtime resulting in deactivated UI connections when using Qt6.
This fix just rename the slot so that it could be connected automatically to the correct signal.
> [gui] fix Qt6 deprecated signal usage

- cmake/Config.cmake.in
- cmake/Windeployqt.cmake
Bug fix, 
cmake configuration fails with new qt, when using radium as an external lib for app.
(LOCATION undef on Qt::Core, windeploy qt fails to find QtFunctions.
seems to work
> [cmake] fix cmake config asking qt location.

- doc/main.md
- src/Core/Asset/HandleData.inl
- src/Core/Asset/LightData.inl
- src/Core/Geometry/IndexedGeometry.hpp
- src/Core/Geometry/IndexedGeometry.inl
- src/Core/Utils/Attribs.cpp
- src/Core/Utils/Attribs.hpp
- src/Core/Utils/Attribs.inl
- src/Core/Utils/ContainerIntrospectionInterface.hpp
- src/Core/Utils/ObjectWithSemantic.hpp
- src/Engine/Data/Mesh.inl
- src/Engine/Scene/GeometrySystem.cpp
- src/Gui/Viewer/Viewer.cpp
- tests/unittest/Core/indexview.cpp
- tests/unittest/Core/observer.cpp
This PR adds access to the indexLayer of a mesh with small introspection capabilities.
This allows to use any indexLayer transparently when using low level  rendering API (e.g. OpenGL, Vulkan, embree, ...).
The way one can introspect the indexLayer is the same than any mesh attribute.
> [core] IndexLayer memory layout introspection

- .github/workflows/push-master-ci.yml
This PR use PAT to allow push VERSION file on a protected branch.
The commit message contains [skip ci] so CI is not triggered by this commit (otherwise we get an infinite loop).
> [github] use token

- src/Gui/Viewer/RotateAroundCameraManipulator.cpp
- src/Gui/Viewer/RotateAroundCameraManipulator.hpp
feature.
RotateAroundCameraManipulator do not override fitScene, hence pivot point is not set to scene center. 
fitScene use scene center as default pivot point
> [gui] add RotateAroundCameraManipulator::fitScene.

- tests/ExampleApps/HeadlessLibAndApp/libHeadless/RadiumHeadless/OpenGLContext/OpenGLContext.cpp
A very small improvement on the error message displayed when Radium-headless is unable to create the OpenGL Context.
> [tests][headless] improve error message when OpenGL context can not be created.

- .github/workflows/push-master-ci.yml
- .github/workflows/push-rc-ci.yml
doc is deployed only if all builds pass. Sometimes (as last time) a build job fails due to network error. 
Change job dependecy to deploy doc even if build fail.
Nope.
> [github] Update ci job dependecies, to trigger doc in // of build.

- src/Engine/Scene/SkinningComponent.cpp
This PR add default choices for two switches in SkiningComponent
No default raise warning (gcc version 10.2.1 20210110 (Debian 10.2.1-6))
New default being LBS and STANDARD
> [engine] add default to skinning switches.

- src/Engine/Rendering/Renderer.cpp
- tests/ExampleApps/EntityAnimationDemo/main.cpp
- tests/unittest/Core/observer.cpp
Remove warnings.
With gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
Renderer.cpp:244:38: warning: missing braces around initializer for ‘std::__array_traits<int, 4>::_Type’ {aka ‘int [4]’} [-Wmissing-braces]
Also fixes two unused warning.
No warning on these inits.
With my setup whole compilation produces 0 gcc warning 
there is still one "information" AutoMoc: RadiumPluginInterface.hpp:0: Note: No relevant classes found. No output generated.
Not tested on other compilers, but picking …
> Fix warnings

- cmake/filelistGui.cmake
- src/Gui/Viewer/WindowQt.hpp
- src/Gui/Viewer/WindowQt.inl
Add scoped context behavior. One can ask WindowQt an OpengGLContext than is bound at variable creation, and unbound when the variable is deleted (end of scope).
Have to manage context activation with makeCurrent and doneCurrent.
In a block, some gl related variable might be deleted on block end, while the doneCurrent have to be called before block end explicitly, see #912 .
Such block binded context are obtained as an ScopedContext object with WindowQt::createScopedContext, ScopedContext ctor calls …
> Scoped context

- src/Engine/Data/RenderParameters.hpp
- src/Gui/Viewer/Viewer.hpp
Feature : make Viewer::update(dt) virtual, so that derived viewer can perform custom update. 
updates are only available with handle*event or tasks, but viewer could not update on its own.
Useful for small viewer related stuff one do not want to put on the engine side.
> Viewer virtual update

- scripts/list_dep.py
bug fix in script
scripts/list_dep.py was not udpated to take into account cmake lint which introduce linebreaks in cmake commands
read whole text (and not line by line) to preform regex search
> [scripts] update list dep to new cmake format

- src/Headless/CLIViewer.hpp
- src/Headless/CLIViewer.inl
- src/Headless/OpenGLContext/OpenGLContext.cpp
- tests/ExampleApps/HeadlessDemo/main.cpp
Closes #938 
When using CLIViewer as a window on a non-Qt platform, there is no way to add event processing callback to develop interactive application.
This PR proposes a quick fix and will serve to fully test the event management capabilities on CLIViewer before being merged.
This PR allows applications using headless CLIViewer to add event processing callbacks on the optionally given window
Callback attachment to the window are available but the window is private and …
> [headless] allow to access the optional window for event processing

- .github/workflows/build-matrix.yml
- doc/basics.md
- doc/basics/compilation.md
- doc/basics/dependencies.md
- external/CMakeLists.txt
- src/CMakeLists.txt
- src/Config.cmake.in
- tests/CMakeLists.txt
- tests/integration/CMakeLists.txt
Doc fix. PR #935 states that external can be built in a subdir of radium source tree, but it fails when installing (something related to rpath ?)
This PR revert the doc to state that the external dep have to be built outside source tree.
It also add an integration test (which actually pass even if external are installed in radium source tree, because it runs in radium build tree)
Add a CI test to try to run CoreExampleApps from build and install dirs.
> Fix external compile

- .github/workflows/pull-request-ci.yml
- .github/workflows/push-master-ci.yml
- .github/workflows/push-rc-ci.yml
Even if CI coverage is meaningfull only if CI builds succeded, process them in parallel can save some time.
This PR remove coverage needs of call_build
> [github] trigger coverage without waiting other builds

- src/Engine/Data/ShaderConfiguration.cpp
- src/Engine/Data/ShaderConfiguration.hpp
- src/Engine/Data/ShaderProgram.hpp
- src/Engine/RadiumEngine.cpp
instead of default `#version 410` added to all managed shaders, use the GLSL version corresponding to the OpenGL version of the context bound when initializing engine.
shader header default to `#version 410`
shader header default to `#version context-dependant-version`
NO
* **Other …
> Set default GLSL version for shaders according to detected OpenGL context

- examples/HeadlessExample/main.cpp
- examples/HelloRadium/main.cpp
- src/Engine/Data/ShaderConfiguration.cpp
- src/Engine/Data/ShaderConfiguration.hpp
- src/Engine/RadiumEngine.cpp
- src/Engine/RadiumEngine.hpp
- src/Gui/BaseApplication.cpp
- src/Gui/BaseApplication.hpp
- src/Headless/CLIViewer.cpp
- src/Headless/CLIViewer.hpp
- src/Headless/OpenGLContext/OpenGLContext.cpp
- src/Headless/OpenGLContext/OpenGLContext.hpp
Follow up of #965.
OpenGL version could be requested and checked when creating an application (Qt based or headless/glfw based)
OpenGL version is fixed to some varying recommended version (4.4 for Qt apps, 4.1 for headless/glfw)
OpenGL version might be reuested by users when creating an application (Qt or headless/glfw). If no specific version is given, the default is the minimum openGL required version for …
> Allow applications to set the opengl version according to their requirements

- .github/workflows/build-matrix.yml
Update github action install-qt-action v2 to v3,
v2 has some issue with python setup on mac os runner, see [here](https://github.com/STORM-IRIT/Radium-Engine/runs/7932973246?check_suite_focus=true) (excerpt below).
v3 fix this issue.
```
WARNING: Requested bcj-cffi<0.6.0,>=0.5.1 from https://files.pythonhosted.org/packages/97/9c/681442a5b3a5bb3a1210a8ddc6cc6f6a47ea90834b80daa15af767b1c29a/bcj-cffi-0.5.1.tar.gz (from py7zr==0.16.1), but installing version 0.0.0
Discarding https://files.pythonhosted.org/packages/97/9c/681442a5b3a5bb3a1210a8ddc6cc6f6a47ea90834b80daa15af767b1c29a/bcj-cffi-0.5.1.tar.gz (from https://pypi.org/simple/bcj-cffi/): Requested bcj-cffi<0.6.0,>=0.5.1 from https://files.pythonhosted.org/packages/97/9c/681442a5b3a5bb3a1210a8ddc6cc6f6a47ea90834b80daa15af767b1c29a/bcj-cffi …
```
> [ci] Update install-qt-action version to v3.

- scripts/generateFilelistForModule.sh
Try to fix generate filelist script on macos x
find command print a // if the argument have a trailing /
this pr should fix it.
> [scripts] remove trailing / for find commands

- .github/workflows/build-matrix.yml
- CMakeLists.txt
- doc/basics/compilation.md
- src/Headless/CLIViewer.cpp
- tests/unittest/CMakeLists.txt
- tests/unittest/Engine/materials.cpp
The fix on Headless component allows to run unittests that require OpenGL context and fix a potential memory leak for some applications.
The RADIUM_ENABLE_GL_TESTING cmake option is added to enable OpenGL related unittests.
When running tests that use CLIViewer, as the engine singleton constructed when the CLIViewer is constructed is not destroyed when the CLI Viewer is destroy, the actual version segfault on the next engine singleton creation/deletion.
* **What is the …
> Fix missing engine deletion in CLIVIewer that prevent OpenGL related unittest to work

- external/Core/CMakeLists.txt
- external/Core/patches/eigen.patch
Use tagged version 3.4.0 instead of commit sha for eigen external project.
> [external] update Eigen to last stable release 3.4.0

- .github/workflows/pull-request-ci.yml
Run PR checks agains master PR (not only release candidate)
PR CI checks are only run against RC PR. 
Run PR CI chcckes for agains master PR as well.
When we factorize CI code, and change workflow using RC branch, we start push to master directly.
After some checks, RC to master PR seems to use fast forward, so we can use github PR mechanism here too, and have CI running to check before merging.
> [ci] Run PR checks on master also.

- src/Core/Utils/BijectiveAssociation.hpp
- src/Core/Utils/BijectiveAssociation.inl
- src/Engine/Data/Mesh.hpp
- src/Engine/Data/Mesh.inl
- tests/unittest/Core/bijectiveassociation.cpp
Refactor Engine::Mesh translation table using BijectiveAssociation.
Also add new functionality to meet the needs of Engine::Mesh translation table 
Engine::Mesh translation table use ad hoc std::maps to perform core attrib name to shader attrib name correspondance.
Use BijectiveAssociation code, which was introduce in #950
> Use BijectiveAssociation for mesh translation table

- src/Core/Containers/VariableSet.cpp
- src/Core/Containers/VariableSet.hpp
- src/Core/Utils/StdExperimentalTypeTraits.hpp
- src/Core/filelist.cmake
- tests/unittest/CMakeLists.txt
- tests/unittest/Core/variableset.cpp
First proposal to integrate into Core the management of "variables" from all other components.
A "variable is a mapping between a name and a type to a value.
The intent of this PR is to replace the class ("had-hoc and heavily specialized) RenderParameter to have the opportunity to manage several other variable representation and to simplify the extension of such renderParameter.
TODO
> Core variables

- src/Headless/Config.cmake.in
hot fix,
when using Radium::Headless as a component outside radium build, configure fails since it tries to set_target_property before target is defined.
the fix move the include target file before the set.
> [headless] Move target include before set_target_property

- src/Core/Containers/VariableSet.cpp
- src/Core/Containers/VariableSet.hpp
- tests/unittest/Core/variableset.cpp
Fix remaining bugs in VariableSet
- missing erased on moved containers
- dynamic visitor segfault 
Add the ability to pass user parameter to visitors.
Improve documentation
Question, do we extend the capabilities of VariableSet::TypeList to have something like https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb/openvdb/TypeList.h
Please check if the PR fulfills these …
> Fix Core::VariableSet

- examples/CustomCameraManipulator/main.cpp
- examples/DrawPrimitives/minimalapp.cpp
- examples/DrawPrimitives/minimalapp.hpp
- src/Gui/Configs/default.xml
- src/Gui/Viewer/CameraManipulator.hpp
- src/Gui/Viewer/FlightCameraManipulator.cpp
- src/Gui/Viewer/FlightCameraManipulator.hpp
- src/Gui/Viewer/RotateAroundCameraManipulator.cpp
- src/Gui/Viewer/RotateAroundCameraManipulator.hpp
- src/Gui/Viewer/TrackballCameraManipulator.cpp
- src/Gui/Viewer/TrackballCameraManipulator.hpp
- src/Gui/Viewer/Viewer.cpp
Fix camera manipulators wrt KeyMapping callbacks.
RotateAround was broken since it derives from Trackball, and m_currentAction was out of sync since the use of callback to manager action.
Handle all camera manipulators with callback associated to action.
Also add camera manipulator switch in draw primitive demo, to check the three provided camera manipulator.
For futur PR, maybe remove FlightManipulatorContext, move KeyMappingContext to CameraManipulator, and then #545
> Fix camera

- .github/workflows/deploy-doc.yml
- .github/workflows/manual-doc-artifact-build.yml
- .github/workflows/tmp-check-doc.yml
This PR update doxygen version, it also adds a new github action to test doc creation.
It fixes doxygen missing TOC in markdown doc.
This workflow might be run manually on branches and create an artifact with the produced doc.
I'm not sure it will be ok to be run on PR branch, but is should be, and also can be modified when needed with 
```{.yml}
on:
pull_request:
branches:
- release-candidate
```
see https://build5nines.com/configuring-manual-triggers-in-github-actions-with-workflow_dispatch/
https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
> Ci update doxygen

- CMakeLists.txt
- cmake/CodeCoverage.cmake
- cmake/CompilerOptions.cmake
- examples/HeadlessExample/main.cpp
- src/Core/Geometry/MeshPrimitives.cpp
- src/Core/Geometry/OpenMesh.hpp
- src/Core/Math/LinearAlgebra.hpp
- src/Engine/Data/EnvironmentTexture.cpp
- src/Engine/Data/ShaderProgramManager.hpp
- src/Engine/Data/TextureManager.cpp
- src/Engine/Rendering/ForwardRenderer.cpp
- src/Engine/Rendering/ForwardRenderer.hpp
- src/Engine/Scene/ComponentMessenger.cpp
- src/Gui/BaseApplication.hpp
- src/Gui/CMakeLists.txt
- src/Gui/Viewer/Viewer.cpp
- src/Headless/CLI/TypeTools.hpp
- src/Headless/CLIViewer.cpp
- src/Headless/CLIViewer.hpp
- src/PluginBase/CMakeLists.txt
- tests/CMakeLists.txt
- tests/unittest/CMakeLists.txt
- tests/unittest/Core/variableset.cpp
Related to coverage, it was not working on my side, maybe related to qt6 moc, but I did not dig more than that to find why.
[cmake] CMAKE_AUTOMOC_PATH_PREFIX to fix coverage.
[cmake] Update coverage exclude and basedir.
[cmake] updates CodeCoverage.cmake according to upstream and local fixes.
[cmake] Code coverage verbose message without STATUS.
[tests][cmake] parrallel ctest.
About warnings
[core][engine][headless][tests] fix warnings.
[cmake] do not warn missing default on switch.
Apout cli
[examples] …
> Small fixes and improvement.

- .github/workflows/build-matrix.yml
- .github/workflows/pull-request-ci.yml
- .github/workflows/push-master-ci.yml
- .github/workflows/push-rc-ci.yml
- cmake/QtFunctions.cmake
- cmake/Windeployqt.cmake
- doc/basics/commandline.md
- doc/basics/details.md
- doc/basics/troubleshooting.md
- doc/developer/cmakeutilities.md
- doc/developer/plugin.md
- examples/PluginsWithLib/Downstream/README.md
- examples/PluginsWithLib/Upstream/README.md
- external/Gui/CMakeLists.txt
- src/Core/Asset/Camera.cpp
- src/Gui/Timeline/TimelineScrollArea.cpp
- src/Gui/Utils/KeyMappingManager.cpp
- src/Gui/Viewer/WindowQt.cpp
- src/Gui/Widgets/ControlPanel.cpp
Both qt5 and qt6 are supported, but the CI lacks support of qt5 (see #1081)
If there is Qt5 specific configuration (in cmake) or code (in c++), user codes have to be updated.
> 1081 remove qt5 support

- .github/workflows/deploy-doc.yml
- .github/workflows/pull-request-ci.yml
PR #1085 broke doxygen doc build on CI, 
This PR add PR CI doc generation (as downloadable artifact) to check doc before merge.
It also update runner (might be the root issue).
> [ci] fix deploy doc.

- .github/workflows/deploy-doc.yml
- .github/workflows/manual-doc-artifact-build.yml
- .github/workflows/pull-request-ci.yml
Remove duplicated code in CI (I had forgotten we have a manual doc build action).
> [ci] Manual doc build uses deploy-doc, remove doc build from pr ci.

- src/Dataflow/QtGui/GraphEditor/GraphEditorWindow.cpp
This PR allows to edit the instance name of a node in graph editor and, when saving a graph, set the instance and display name to the filename if they are empty.
see issue #1101
editing instance name is now enabled, setting empty instance name to valid instancename is done when saving, thus allowing to load as embeded graph.
> Fix embed graph edit (issue #1101)
